### ISSUE TITLE
unable to update from 0.91.4 to 0.92.2

### ISSUE THREAD

**Issue by partymike** [home-assistant/hassio#1075]
click the update button but update fails and it reverts back to 0.91.4, no errors are logged

current version 0.91.4

hassio nuc version on ubuntu server 18.04

19-05-07 10:43:13 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.92.2
19-05-07 10:43:13 INFO (SyncWorker_10) [hassio.docker.interface] Update image homeassistant/intel-nuc-homeassistant:0.91.4 to homeassistant/intel-nuc-homeassistant:0.92.2
19-05-07 10:43:13 INFO (SyncWorker_10) [hassio.docker.interface] Pull image homeassistant/intel-nuc-homeassistant tag 0.92.2.
19-05-07 10:44:28 INFO (SyncWorker_10) [hassio.docker.interface] Tag image homeassistant/intel-nuc-homeassistant with version 0.92.2 as latest
19-05-07 10:44:28 INFO (SyncWorker_10) [hassio.docker.interface] Stop homeassistant application
19-05-07 10:44:59 INFO (SyncWorker_10) [hassio.docker.interface] Clean homeassistant application
19-05-07 10:44:59 INFO (SyncWorker_10) [hassio.docker.interface] Cleanup images: ['homeassistant/intel-nuc-homeassistant:0.91.4']
19-05-07 10:45:00 INFO (SyncWorker_21) [hassio.docker.homeassistant] Start homeassistant homeassistant/intel-nuc-homeassistant with version 0.92.2
19-05-07 10:45:02 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-05-07 10:45:02 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-05-07 10:45:02 INFO (MainThread) [hassio.auth] Home Assistant not running, check cache
19-05-07 10:45:02 INFO (MainThread) [hassio.auth] Cache hit for mqtt
19-05-07 10:55:02 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup!
19-05-07 10:55:02 CRITICAL (MainThread) [hassio.homeassistant] HomeAssistant update fails -> rollback!
19-05-07 10:55:02 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.91.4
19-05-07 10:55:02 INFO (SyncWorker_30) [hassio.docker.interface] Update image homeassistant/intel-nuc-homeassistant:0.92.2 to homeassistant/intel-nuc-homeassistant:0.91.4
19-05-07 10:55:02 INFO (SyncWorker_30) [hassio.docker.interface] Pull image homeassistant/intel-nuc-homeassistant tag 0.91.4.
19-05-07 10:56:19 INFO (SyncWorker_30) [hassio.docker.interface] Tag image homeassistant/intel-nuc-homeassistant with version 0.91.4 as latest
19-05-07 10:56:19 INFO (SyncWorker_30) [hassio.docker.interface] Stop homeassistant application
19-05-07 10:56:20 INFO (SyncWorker_30) [hassio.docker.interface] Clean homeassistant application
19-05-07 10:56:20 INFO (SyncWorker_30) [hassio.docker.interface] Cleanup images: ['homeassistant/intel-nuc-homeassistant:0.92.2']
19-05-07 10:56:21 INFO (SyncWorker_9) [hassio.docker.homeassistant] Start homeassistant homeassistant/intel-nuc-homeassistant with version 0.91.4
19-05-07 10:56:23 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-05-07 10:56:23 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-05-07 10:56:23 INFO (MainThread) [hassio.auth] Home Assistant not running, check cache
19-05-07 10:56:23 INFO (MainThread) [hassio.auth] Cache hit for mqtt
19-05-07 10:56:56 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-05-07 10:56:56 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.91.4

**Description of problem:**

trying to update to the latest version but update fails for no logged reason other than a timeout so reverts back to old version - any suggestions on how to proceed?

**Comment by frenck** [comment]
This usually means the upgrade failed because of your configuration. Use the configuration check add-on to test your configuration before the upgrade.

**Comment by partymike** [comment]
all checked and I get the green "configuration valid!"

**Comment by frenck** [comment]
Anything in your Home Assistant log file when it rolls back?

**Comment by partymike** [comment]
I can see the following:

2019-05-07 13:13:43 ERROR (SyncWorker_8) [homeassistant.components.netatmo.climate] No default_home in HomeData.
2019-05-07 13:13:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3042, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'--only-b'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/requirements.py", line 80, in loadable
    req = pkg_resources.Requirement.parse(package)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3035, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3044, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'--only-b'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 56, in async_setup_component
    return await task  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 131, in _async_setup_component
    await async_process_deps_reqs(hass, config, domain, component)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 252, in async_process_deps_reqs
    hass, name, module.REQUIREMENTS)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/homeassistant/requirements.py", line 40, in async_process_requirements
    if await pkg_cache.loadable(req):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/requirements.py", line 84, in loadable
    req = pkg_resources.Requirement.parse(urlparse(package).fragment)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in parse
    req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)

**Comment by frenck** [comment]
This seems to be an issue with the Netatmo integration, not Hass.io.

Try to disable those integrations and see if you can reactivate them after the upgrade.
If the issues persist, you might want to file an issue on our main repository:

https://github.com/home-assistant/home-assistant

Since, well, this is not an Hass.io related issue.

**Comment by partymike** [comment]
ok, that didn't work so I'll open support issue over there - thanks for the assistance :-)

**Comment by frenck** [comment]
No problem! I hope you'll get it resolved soon!
