### ISSUE TITLE
Failed to fetch add-on info

### ISSUE THREAD

**Issue by det-peralta** [home-assistant/hassio#1085]
**Home Assistant release with the issue:**
0.93.0

**Operating environment (HassOS/Generic):**
Hassio

**Supervisor logs:**
`KeyError: 'a21c4976'
19-05-16 17:59:47 INFO (SyncWorker_17) [hassio.docker.interface] Restart homeassistant/qemux86-64-homeassistant
19-05-16 18:00:16 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-05-16 18:00:53 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 158, in list
    ATTR_NAME: repository.name,
  File "/usr/src/hassio/hassio/store/repository.py", line 41, in name
    return self.data.get(ATTR_NAME, UNKNOWN)
  File "/usr/src/hassio/hassio/store/repository.py", line 36, in data
    return self.sys_store.data.repositories[self.slug]
KeyError: 'a21c4976'
19-05-16 18:00:58 INFO (SyncWorker_4) [hassio.docker.interface] Restart homeassistant/qemux86-64-homeassistant
19-05-16 18:01:24 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-05-16 18:02:01 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 158, in list
    ATTR_NAME: repository.name,
  File "/usr/src/hassio/hassio/store/repository.py", line 41, in name
    return self.data.get(ATTR_NAME, UNKNOWN)
  File "/usr/src/hassio/hassio/store/repository.py", line 36, in data
    return self.sys_store.data.repositories[self.slug]
KeyError: 'a21c4976'
19-05-16 18:18:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 158, in list
    ATTR_NAME: repository.name,
  File "/usr/src/hassio/hassio/store/repository.py", line 41, in name
    return self.data.get(ATTR_NAME, UNKNOWN)
  File "/usr/src/hassio/hassio/store/repository.py", line 36, in data
    return self.sys_store.data.repositories[self.slug]
KeyError: 'a21c4976'
19-05-16 18:22:36 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 158, in list
    ATTR_NAME: repository.name,
  File "/usr/src/hassio/hassio/store/repository.py", line 41, in name
    return self.data.get(ATTR_NAME, UNKNOWN)
  File "/usr/src/hassio/hassio/store/repository.py", line 36, in data
    return self.sys_store.data.repositories[self.slug]
KeyError: 'a21c4976'
19-05-16 18:25:36 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 158, in list
    ATTR_NAME: repository.name,
  File "/usr/src/hassio/hassio/store/repository.py", line 41, in name
    return self.data.get(ATTR_NAME, UNKNOWN)
  File "/usr/src/hassio/hassio/store/repository.py", line 36, in data
    return self.sys_store.data.repositories[self.slug]
KeyError: 'a21c4976'`

**Description of problem:**

Cannot open Add-on Store tab.

Hassio -> Add-on Store

**Comment by pvizeli** [comment]
Can you explain how do run into that issue?

**Comment by det-peralta** [comment]
With the 0.93.1 update, i can open again, Add-on Store tab.

I think this was a problem adding a repository
