### ISSUE TITLE
hassio 0.94.1 not loading August Lock, iOS, and device tracker after update

### ISSUE THREAD

**Issue by jeffl78** [home-assistant/hassio#1123]
I'm running hass.io via docker on a raspberry pi 3 and after updating to 0.94.1 from 0.93.2 not land now I get a notification from HA that August Lock, iOS, and device tracker are not loading.  I realize that this may need to be broke into three separate issue reports, and also noticed that my configured components do not show up when I browse to the integration page but I don't think this is related and will make a separate issue for this irregularity.   Below I have listed some of the related log files but I have sliced and diced them from my original logs so I hope I have posted all related errors, though I believe I have.  I will be checking breaking changes but honestly besides device tracker I don't think I there is anything listed that may related to these errors

My system health:

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
version | 0.94.1
virtualenv | false

![Screenshot 2019-06-09 at 6 04 32 PM](https://user-images.githubusercontent.com/29915517/59165439-297f6400-8ae1-11e9-8fa5-00466b71651f.png)

.

August:

2019-06-09 12:04:53 ERROR (MainThread) [homeassistant.setup] Error during setup of component august
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 166, in setup
    return setup_august(hass, config, api, authenticator)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 113, in setup_august
    hass, api, authentication.access_token)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 177, in __init__
    self._doorbells = self._api.get_doorbells(self._access_token) or []
  File "/usr/local/lib/python3.7/site-packages/august/api.py", line 146, in get_doorbells
    access_token=access_token).json()
  File "/usr/local/lib/python3.7/site-packages/august/api.py", line 296, in _call_api
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-production.august.com/users/doorbells/mine

iOS:

2019-06-09 12:04:58 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of ios. Setup failed for dependencies: device_tracker
2019-06-09 12:04:58 ERROR (MainThread) [homeassistant.setup] Setup failed for ios: Could not set up all dependencies.

2019-06-09 17:32:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 66, in get
    } for entry in hass.config_entries.async_entries()])
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 66, in <listcomp>
    } for entry in hass.config_entries.async_entries()])
KeyError: 'ios'

Device Tracker:

2019-06-09 12:04:57 ERROR (MainThread) [homeassistant.setup] Error during setup of component device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/__init__.py", line 115, in async_setup
    legacy_platforms = await setup.async_extract_config(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 109, in async_extract_config
    platform.name, platform.type))
ValueError: Unable to determine type for owntracks: None
2019-06-09 12:04:58 WARNING (MainThread) [homeassistant.setup] Setup of wink is taking over 10 seconds.
2019-06-09 12:04:58 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of ios. Setup failed for dependencies: device_tracker
2019-06-09 12:04:58 ERROR (MainThread) [homeassistant.setup] Setup failed for ios: Could not set up all dependencies.

**Comment by jeffl78** [comment]
The fix is listed here:

https://www.reddit.com/r/homeassistant/comments/byt6g0/hassio_0941_not_loading_august_lock_ios_and/

**Comment by jeffl78** [comment]
Closing because the fix is linked above
