### ISSUE TITLE
Gstreamer component error

### ISSUE THREAD

**Issue by Romkabouter** [home-assistant/hassio#1155]
**Home Assistant release with the issue:**
0.95.4

**Operating environment (HassOS/Generic):**
HassOS

**Supervisor logs:**
Error while setting up platform gstreamer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/gstreamer/media_player.py", line 31, in setup_platform
    from gsp import GstreamerPlayer
  File "/usr/local/lib/python3.7/site-packages/gsp/__init__.py", line 11, in <module>
    import gi  # pylint: disable=import-error
ModuleNotFoundError: No module named 'gi'

**Description of problem:**
When adding gstreamer to the configuration.yaml on HassIO, the above error is generated.
Seems the module gi is not being installed

**Comment by pvizeli** [comment]
Yes, we have no gstream installed. Please use vlc and remote-vlc add-on

**Comment by Romkabouter** [comment]
"VLC currently not supported with Hass.io"
