### ISSUE TITLE
Partial failure of upgrade to 168

### ISSUE THREAD

**Issue by stampeder** [home-assistant/hassio#1158]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

**Comment by stampeder** [comment]
Currently running version 168. Did an upgrade of home-assistant from 9.3 to 9.5.4 now get error loading page on MAP, Logbook, History, Configuration and all the Dev tools.
Any help would be greatly appreciated.
Running Hassio on Docker using Ubuntu 18.04.
Everything was working fine prior to upgrade.
Thanks.
Glenn.

**Comment by frenck** [comment]
Please provide logs, there is not much I can do with "It doesn't work".

**Comment by stampeder** [comment]
Here is the log file:
2019-07-14 10:07:28 ERROR (SyncWorker_4) [homeassistant.components.radiotherm.climate] Unable to connect to Radio Thermostat: 10.10.10.115
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/radiotherm/climate.py", line 103, in setup_platform
    tstat = radiotherm.get_thermostat(host)
  File "/usr/local/lib/python3.7/site-packages/radiotherm/__init__.py", line 80, in get_thermostat
    model = initial.model.get('raw')
  File "/usr/local/lib/python3.7/site-packages/radiotherm/fields.py", line 45, in __get__
    response = instance.get(self.url)
  File "/usr/local/lib/python3.7/site-packages/radiotherm/thermostat.py", line 35, in get
    return request.urlopen(url)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] Host is unreachable>
2019-07-14 10:07:31 ERROR (SyncWorker_4) [homeassistant.components.radiotherm.climate] Unable to connect to Radio Thermostat: 10.10.10.122
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/radiotherm/climate.py", line 103, in setup_platform
    tstat = radiotherm.get_thermostat(host)
  File "/usr/local/lib/python3.7/site-packages/radiotherm/__init__.py", line 80, in get_thermostat
    model = initial.model.get('raw')
  File "/usr/local/lib/python3.7/site-packages/radiotherm/fields.py", line 45, in __get__
    response = instance.get(self.url)
  File "/usr/local/lib/python3.7/site-packages/radiotherm/thermostat.py", line 35, in get
    return request.urlopen(url)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] Host is unreachable>
2019-07-14 10:08:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/discovery/__init__.py", line 201, in scan_devices
    results = await hass.async_add_job(_discover, netdisco)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/discovery/__init__.py", line 228, in _discover
    for service in netdisco.get_info(disc):
  File "/usr/local/lib/python3.7/site-packages/netdisco/discovery.py", line 104, in get_info
    return self.discoverables[dis].get_info()
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/__init__.py", line 28, in get_info
    return [self.info_from_entry(entry) for entry in self.get_entries()]
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/__init__.py", line 28, in <listcomp>
    return [self.info_from_entry(entry) for entry in self.get_entries()]
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/samsung_tv.py", line 22, in info_from_entry
    if info[ATTR_NAME].startswith(FORCED_NAME_PREFIX):
KeyError: 'name'

Hope this helps.
Glenn.

**Comment by frenck** [comment]
We have seen this behavior now a couple of times, but no direct lead to things. 
It sounds lame, but up until this point, a full reboot of the host system seems to solve the issue.

**Comment by stampeder** [comment]
Thanks for the reply Frank. Not sure if it's a good thing or not but it is an answer. It is just not my day. This problem and also I got a strange thing going on with Portainer which I use as my docker management system for Home Assistant. It never rains but it pours. Thanks again will try the reboot.

**Comment by pvizeli** [comment]
we are now on 170 and I see none reports anymore
