### ISSUE TITLE
hassio-supervisor socat process dies and can't come back w/ apparmor rules

### ISSUE THREAD

**Issue by superm1** [home-assistant/hassio#1169]
**Home Assistant release with the issue:**
0.96.2

**Operating environment (HassOS/Generic):**
Generic install on top of Ubuntu 18.04 server.
Using docker snap from from stable snap channel (`Docker version 18.06.1-ce, build e68fc7a`)

**Supervisor logs:**
Snippet from relevant part:
```
19-07-20 01:38:50 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<DNSForward.stop() done, defined at /usr/src/hassio/hassio/misc/dns.py:34> exception=ProcessLookupError()>
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/misc/dns.py", line 40, in stop
    self.proc.kill()
  File "/usr/local/lib/python3.7/asyncio/subprocess.py", line 134, in kill
    self._transport.kill()
  File "uvloop/handles/process.pyx", line 637, in uvloop.loop.UVProcessTransport.kill
  File "uvloop/handles/process.pyx", line 385, in uvloop.loop.UVProcessTransport._check_proc
ProcessLookupError
```

**Description of problem:**
I'm finding that on a fresh boot everything is working well, but after some period of time the `socat` process in hassio-supervisor disappears and doesn't come back.  This  leads to the homeassistant container having dns failures which have been detailed on several other bugs.

Due to the apparmor rules it's a little difficult to determine this though:
```
$ sudo docker exec -it hassio_supervisor ps auxf                                                                                                                            OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 21\"": unknown     
```

If I turn off the apparmor rules I can see the socat process is indeed missing:
```
# sudo apparmor_parser -R -W -L "/root/snap/current/hassio/apparmor/cache" "/root/snap/current/hassio/apparmor/hassio-supervisor"        
$ sudo docker exec -it hassio_supervisor ps auxf                                                                                                                            PID   USER     TIME  COMMAND                                                                                                                                                                      1 root      0:24 /usr/local/bin/python3 -m hassio                                                                                                                                             8 root      0:00 udevd --daemon                                                                                                                                                             115 root      0:00 ps auxf                                                                                                                                                                    122 root      0:00 udevd --daemon                             
```

Manually starting the `socat` process up gets things back to life while apparmor is stopped. 
If apparmor is running, I notice the following audit messages in dmesg:
```
[59056.762413] audit: type=1400 audit(1563567209.000:276): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="hassio-supervisor///usr/bin/socat" pid=31339 comm="apparmor_parser"
[59057.689642] audit: type=1400 audit(1563567209.924:277): apparmor="DENIED" operation="open" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/3d5604f7ccad1e7c2fb57ace77938716e6444075b62c51ff9698ab499dce4c2a/usr/lib/libreadline.so.8.0" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[59057.689671] audit: type=1400 audit(1563567209.924:278): apparmor="DENIED" operation="open" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/97fad04651fc3aad3b81f601308c975653e9a5dac39deeb9d48c7ec1d711dcca/lib/libssl.so.1.1" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[59057.689897] audit: type=1400 audit(1563567209.924:279): apparmor="DENIED" operation="open" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/97fad04651fc3aad3b81f601308c975653e9a5dac39deeb9d48c7ec1d711dcca/lib/libssl.so.1.1" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[59057.689950] audit: type=1400 audit(1563567209.924:280): apparmor="DENIED" operation="open" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/97fad04651fc3aad3b81f601308c975653e9a5dac39deeb9d48c7ec1d711dcca/lib/libcrypto.so.1.1" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[59057.690106] audit: type=1400 audit(1563567209.924:281): apparmor="DENIED" operation="open" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/97fad04651fc3aad3b81f601308c975653e9a5dac39deeb9d48c7ec1d711dcca/lib/libcrypto.so.1.1" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[59057.690621] audit: type=1400 audit(1563567209.928:282): apparmor="DENIED" operation="file_mprotect" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/97fad04651fc3aad3b81f601308c975653e9a5dac39deeb9d48c7ec1d711dcca/lib/ld-musl-x86_64.so.1" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[59057.691115] audit: type=1400 audit(1563567209.928:283): apparmor="DENIED" operation="file_mprotect" profile="hassio-supervisor///usr/bin/socat" name="/var/snap/docker/common/var-lib-docker/aufs/diff/63869fe92dece23550a7b3bfc4bdbdfc8044bd6c5e68f195291f54439a92264f/usr/bin/socat" pid=31372 comm="socat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

I did confirm I have the same version of apparmor rules as https://version.home-assistant.io/apparmor.txt exists today,

**Comment by pvizeli** [comment]
That is a aufs issue. Move to official overlay2 storage driver from kernel and that will solve this

**Comment by superm1** [comment]
At least from what I find docker 18.06 prefers aufs, newer versions will default to overlay2.  I upgraded to 18.09 and ran into a bunch of other problems getting containers to start.  Is it not possible to support appamor with 18.06 + aufs?

**Comment by frenck** [comment]
aufs is deprecated and for Docker 19.03 is will throw warnings. Please move away from it.
