### ISSUE TITLE
Hass.io ver .97 WINK and ALexa issues

### ISSUE THREAD

**Issue by franmiele** [home-assistant/hassio#1192]
**Home Assistant release with the issue:**
20190805.0

**Operating environment (HassOS/Generic):**
Raspberry pi3 witj HASS.io image

**Supervisor logs:**
19-08-08 20:00:35 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-08-08 20:00:35 INFO (MainThread) [hassio.addons] Phase 'application' start 3 add-ons
19-08-08 20:00:38 INFO (SyncWorker_14) [hassio.docker.addon] Start Docker add-on hassioaddons/node-red-armv7 with version v4.0.6
19-08-08 20:00:40 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-configurator with version 3.4
19-08-08 20:00:40 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on hassioaddons/log-viewer-armv7 with version v0.6.1
19-08-08 20:00:43 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nodered
19-08-08 20:00:45 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
19-08-08 20:00:45 INFO (MainThread) [hassio.core] Hass.io is up and running
19-08-08 20:00:45 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_logviewer
19-08-08 20:01:44 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-08-08 20:01:44 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-08-08 20:01:45 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-08-08 20:01:45 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running

**Description of problem:**
have a notice saying could not setup wink. I have deleted the .wink config and re-authorized but still doesn't work. Also, it is affecting my Amazon devices. It some how stops my voice commands from working. If I shutdown Hass.io the Amazon stuff works fine

**Comment by l1c2d3** [comment]
I'm having the same problem with Wink.
Apparently, it was a coincidence that it stopped working after the update, because I tried in a test machine using v .95.4, and I got the same errors.

**Logs:**

2019-08-08 18:30:08 ERROR (MainThread) [homeassistant.setup] Error during setup of component wink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/wink/__init__.py", line 368, in setup
    sub_details = pywink.get_subscription_details()
  File "/usr/local/lib/python3.7/site-packages/pywink/api.py", line 662, in get_subscription_details
    response_dict = wink_api_fetch()
  File "/usr/local/lib/python3.7/site-packages/pywink/api.py", line 696, in wink_api_fetch
    raise WinkAPIException("Unexpected")
pywink.api.WinkAPIException: Unexpected
