### ISSUE TITLE
Docker Image not found (homeassistant/qemux86-64-homeassistant:0.98.0)

### ISSUE THREAD

**Issue by LukasQ** [home-assistant/hassio#1268]
Hi there

while updating to 0.98.0 I receive the messages:
```
19-08-29 13:11:15 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-08-29 13:11:27 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.98.0
19-08-29 13:11:27 INFO (SyncWorker_1) [hassio.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.97.2 to homeassistant/qemux86-64-homeassistant:0.98.0
19-08-29 13:11:27 INFO (SyncWorker_1) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.98.0.
19-08-29 13:13:11 ERROR (SyncWorker_1) [hassio.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.98.0 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.98.0: No such image: homeassistant/qemux86-64-homeassistant:0.98.0").
19-08-29 13:13:11 WARNING (MainThread) [hassio.homeassistant] Update Home Assistant image fails
19-08-29 13:13:11 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<process_lock.<locals>.wrap_api() done, defined at /usr/src/hassio/hassio/utils/__init__.py:20> exception=HomeAssistantUpdateError()>
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/utils/__init__.py", line 29, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/homeassistant.py", line 335, in update
    raise HomeAssistantUpdateError()
hassio.exceptions.HomeAssistantUpdateError
```
Which is strange, because 
1) HA finds the version json (so internet access is established)
2) I can lookup the docker repo on my ha host (official VHDX deployment), 
3) pull the image from another machine

Update to 0.97.2 with supervisor 179 worked.

**Comment by LukasQ** [comment]
`hassio supervisor repair` did the trick. The supervisor repaired some add-ons and reinstalled the CLI. After that, the update run without problems.
Still confused, why this happened.

**Comment by pvizeli** [comment]
Did pass the version to updater or did you call simple update?

**Comment by LukasQ** [comment]
nope, just straight forward through GUI and through SSH. Both methods didn't work.
After the repair, both worked.

**Comment by HunterDG** [comment]
This is again happening for me, and `ha su repair` is not resolving the issue since 0.106.5

```20-03-20 17:51:22 INFO (MainThread) [supervisor.homeassistant] Update Home Assistant to version 0.107.2
20-03-20 17:51:22 INFO (SyncWorker_5) [supervisor.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.106.5 to homeassistant/qemux86-64-homeassistant:0.107.2
20-03-20 17:51:22 INFO (SyncWorker_5) [supervisor.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.107.2.
20-03-20 17:51:52 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.107.2 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.107.2: No such image: homeassistant/qemux86-64-homeassistant:0.107.2").
20-03-20 17:51:52 WARNING (MainThread) [supervisor.homeassistant] Update Home Assistant image fails```

**Comment by frenck** [comment]
@HunterDG Please don't dig up old issues. This one has been closed for months. Instead, create a new issue.

Furthermore, the openings post of this issue shows a stack trace as part of the problem, your logs do not and is most likely not even the issue or related.

In 99% of the case where a 404 is thrown, it means you are low on disk space. It needs enough space to be able to download, extract and install it next to the current running installation.

If it is still an issue after checking that, please file a new issue.

Thanks 👍
