### ISSUE TITLE
Alternative: install on a generic Linux host failed

### ISSUE THREAD

**Issue by rchovan** [home-assistant/hassio#1361]
Alternative: install on a generic Linux host failed. Used instruction from page https://www.home-assistant.io/hassio/installation/

**Home Assistant release with the issue:**
Installation failed, HA not installed.

**Operating environment (HassOS/Generic):**
Debian bullseye/sid, 64bit, 

**Supervisor logs:**
root@nas:/opt# docker container logs hassio_supervisor
```
19-11-03 20:07:34 INFO (MainThread) [__main__] Initialize Hass.io setup
19-11-03 20:07:34 INFO (MainThread) [hassio.docker.network] Can't find Hass.io network, create new network
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.39/networks/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/hassio/hassio/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/usr/src/hassio/hassio/bootstrap.py", line 44, in initialize_coresys
    coresys = CoreSys()
  File "/usr/src/hassio/hassio/coresys.py", line 54, in __init__
    self._docker: DockerAPI = DockerAPI()
  File "/usr/src/hassio/hassio/docker/__init__.py", line 36, in __init__
    self.network: DockerNetwork = DockerNetwork(self.docker)
  File "/usr/src/hassio/hassio/docker/network.py", line 24, in __init__
    self.network: docker.models.networks.Network = self._get_network()
  File "/usr/src/hassio/hassio/docker/network.py", line 71, in _get_network
    options={"com.docker.network.bridge.name": DOCKER_NETWORK},
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 154, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i hassio -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))")
19-11-03 20:07:34 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f44305a5bd0>
19-11-03 20:07:34 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f44305a5ad0>

```

**Description of problem:**
Installation of Hass.io failed with above error. Docker images are created, Docker on my system is running, I'm using owncloud docker installation. 

docker images ls
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
root@nas:/home/homeassistant/.homeassistant/scripts# docker images -a
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
homeassistant/amd64-hassio-supervisor   192                 baa670e46e75        9 days ago          250MB
homeassistant/amd64-hassio-supervisor   latest              baa670e46e75        9 days ago          250MB
owncloud/server                         10.2.1              e62d58305067        3 months ago        871MB
webhippie/redis                         latest              92ada940608c        5 months ago        58.4MB
webhippie/mariadb                       latest              f644dacaeb6e        5 months ago        279MB
karalabe/xgo-latest                     latest              5c27fd37fa79        13 months ago       4.92GB
hello-world                             latest              4ab4c602aa5e        14 months ago       1.84kB
```

 docker container ls
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                 PORTS                    NAMES
87418e66191c        owncloud/server:10.2.1     "/usr/bin/entrypoint…"   3 weeks ago         Up 2 weeks (healthy)   0.0.0.0:8080->8080/tcp   owncloud_owncloud_1
dd7429d59e4e        webhippie/redis:latest     "/usr/bin/entrypoint…"   3 weeks ago         Up 2 weeks (healthy)   6379/tcp                 owncloud_redis_1
e349c995e16a        webhippie/mariadb:latest   "/usr/bin/entrypoint…"   3 weeks ago         Up 2 weeks (healthy)   3306/tcp                 owncloud_db_1
```

**Comment by rchovan** [comment]
The cause of this error is installed docker package from repository. Steps to solve:
1. remove docker container and images
2. add manually new docker repository:
```
'example for amd64 arch
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
```
3. install manually package docker-ce, which uninstall docker package. 
4. run again script to install Hass.io
