### ISSUE TITLE
IO Error in ZHA component on HA restart

### ISSUE THREAD

**Issue by sam-ward** [home-assistant/hassio#1367]
**Home Assistant release with the issue:**
0.100.2

**Operating environment (HassOS/Generic):**
hass.io image on RPi 3B+ (hassio version 192)

**Supervisor logs:**

[home-assistant.log](https://github.com/home-assistant/hassio/files/3828574/home-assistant.log)

**Description of problem:**
I have HA setup and running the ZHA component connected to a conbee 2 zigbee stick.  When performing a restart of HA (configuration -> server control -> restart) often, but not always, the ZHA component will not work on the restart.  After the HA devs looked at the logs (home-assistant/home-assistant/issues/28637) it was found that there was an OSError: [Errno 5] I/O error occurring, and they suggested I raise an issue here. The only way to get the ZHA component working again is to do a full reboot of the Pi.

I don't have supervisor logs as yet, but will grab them when it fails again.

**Comment by sam-ward** [comment]
Do any of the dev's have a suggestion how I can troubleshoot this?? as it is very annoying when trying to work on homeassistant.

**Comment by sam-ward** [comment]
I have just upgraded to hass 0.104.1 and hassos 3.8 and the issue still persists.

The following is appears in the hass log file:
`2020-01-18 10:38:41 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.read_parameter' command
2020-01-18 10:38:41 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2124127-if00 for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 103, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 124, in async_initialize
    await self.application_controller.startup(auto_form=True)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 45, in startup
    self.version = await self._api.version()
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 310, in version
    (self._proto_ver,) = await self[NetworkParameter.protocol_version]
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 280, in read_parameter
    r = await self._command(Command.read_parameter, 1 + len(data), param, data)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 210, in _command
    return await asyncio.wait_for(fut, timeout=COMMAND_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError`

**Comment by sam-ward** [comment]
And still getting the problem on 0.105.4, Supervisor 200, and HassOS 3.10.

I would really appreciate some help with this one, as not only does it loose connection to the zigbee stick after an update, but I am also getting intermittent strangeness with ZHA in general (seems like events fire multiple times for no reasons, error messages saying it failed to send a packet etc).  

To me the problem is reminiscent of the ModemManager grabbing the device, but I dont know if this is possible with the HomeAssistant built (formally hassio) or how to check something lower level like that on the Rpi (too many layers of docker containers in the way).

**Comment by basnagel** [comment]
I am having a similar problem in a different setup, not HASS.IO
Some restarts the conbee2 is working, other restarts it is not. A complete reboot of the jail is not neccesary in my case.

Setup is a Freenas server with following HA install https://github.com/tprelog/iocage-homeassistant
It is a python virtualenv

arch | amd64
dev | false
docker | false
hassio | false
os_name | FreeBSD
os_version | 11.3-RELEASE-p6
python_version | 3.7.6
timezone | Europe/Amsterdam
version | 0.106.5
virtualenv | true

zigpy-deconz 0.7.0
zigpy-homeassistant 0.16.0

Log off failing reboot:
2020-03-10 21:21:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zha_map which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-10 21:21:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-10 21:21:37 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.read_parameter' command
2020-03-10 21:21:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry /dev/cuaU0 for zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zha/__init__.py", line 103, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zha/core/gateway.py", line 137, in async_initialize
    await self.application_controller.startup(auto_form=True)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 45, in startup
    self.version = await self._api.version()
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_deconz/api.py", line 310, in version
    (self._proto_ver,) = await self[NetworkParameter.protocol_version]
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_deconz/api.py", line 280, in read_parameter
    r = await self._command(Command.read_parameter, 1 + len(data), param, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_deconz/api.py", line 210, in _command
    return await asyncio.wait_for(fut, timeout=COMMAND_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by pvizeli** [comment]
I sounds like an serial deadlock

**Comment by Adminiuga** [comment]
Didn't we have something similar in the past, when it was initializing too fast? Iirc had to do something with udev?

**Comment by Nixellion** [comment]
+1
```
2020-03-11 23:59:17 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry /dev/ttyUSB0 for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 103, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 137, in async_initialize
    await self.application_controller.startup(auto_form=True)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 135, in startup
    await self.initialize()
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 72, in initialize
    await e.reset()
  File "/usr/local/lib/python3.7/site-packages/bellows/ezsp.py", line 57, in reset
    await self._gw.reset()
  File "/usr/local/lib/python3.7/site-packages/bellows/uart.py", line 222, in reset
    return await asyncio.wait_for(self._reset_future, timeout=RESET_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
