### ISSUE TITLE
Emulated Hue Bridge Crash 0.51

### ISSUE THREAD

**Issue by xeroiv** [home-assistant/hassio#141]
Including the emulated hue bridge component in hassio 0.51 fails to load completely.

```
2017-08-09 00:23:59 INFO (MainThread) [homeassistant.components.http] Serving /api/websocket to 192.168.10.116 (auth: True)
2017-08-09 00:24:00 INFO (MainThread) [homeassistant.components.http] Serving /description.xml to 192.168.10.2 (auth: True)
2017-08-09 00:24:00 INFO (MainThread) [homeassistant.components.http] Serving /api/ to 192.168.10.174 (auth: True)
2017-08-09 00:24:00 INFO (MainThread) [homeassistant.components.http] Serving /api/12345678901234567890/lights to 192.168.10.174 (auth: True)
2017-08-09 00:24:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/__init__.py", line 421, in handle
    result = handler(request, **request.match_info)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/emulated_hue/hue_api.py", line 78, in get
    number = self.config.entity_id_to_number(entity.entity_id)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/emulated_hue/__init__.py", line 196, in entity_id_to_number
    number = str(max(int(k) for k in self.numbers) + 1)
ValueError: max() arg is an empty sequence
2017-08-09 00:37:56 INFO (MainThread) [homeassistant.core] Bus:Handling <Event homeassistant_stop[L]>
2017-08-09 00:37:56 INFO (Thread-2) [homeassistant.components.emulated_hue.upnp] UPNP responder shutting down.
2017-08-09 00:37:58 INFO (MainThread) [homeassistant.core] Bus:Handling <Event homeassistant_close[L]>
```

These errors seem to go away if I remove the newly added rpi-rf switch from my configuration.yaml.  However then my list at /api/pi/lights is empty for the emulated hue bridge.
```
switch screen:
  platform: rpi_rf
  gpio: 17
  switches:
    projector_screen:
      code_on: 1234
      code_off: 1235 
```

**Comment by pvizeli** [comment]
Hass.io have no affect to home-assistant. Please open the issue on home-assistant repositorie
