### ISSUE TITLE
new hass.io install throws errors after reboot

### ISSUE THREAD

**Issue by koen01** [home-assistant/hassio#169]
fresh install off hass.io burnt with etcher. 
After first boot i installed these components

```
{
  "version": "0.58",
  "last_version": "0.58",
  "beta_channel": false,
  "arch": "armhf",
  "timezone": "Europe/Amsterdam",
  "addons": [
    {
      "name": "Check Home Assistant configuration",
      "slug": "core_check_config",
      "description": "Check current Home Assistant configuration against a new version",
      "state": "stopped",
      "version": "0.7",
      "installed": "0.7",
      "repository": "core",
      "logo": true
    },
    {
      "name": "Samba share",
      "slug": "core_samba",
      "description": "Expose Hass.io folders with SMB/CIFS",
      "state": "started",
      "version": "2.0",
      "installed": "2.0",
      "repository": "core",
      "logo": true
    },
    {
      "name": "Mosquitto broker",
      "slug": "core_mosquitto",
      "description": "An Open Source MQTT broker",
      "state": "started",
      "version": "1.0",
      "installed": "1.0",
      "repository": "core",
      "logo": true
    },
    {
      "name": "Bluetooth BCM43xx",
      "slug": "core_bluetooth_bcm43xx",
      "description": "Activate Bluetooth for Broadcom 43xx chips",
      "state": "started",
      "version": "0.7",
      "installed": "0.7",
      "repository": "core",
      "logo": true
    },
    {
      "name": "SSH server",
      "slug": "core_ssh",
      "description": "Allows connections over SSH",
      "state": "started",
      "version": "2.7",
      "installed": "2.7",
      "repository": "core",
      "logo": true
    }
  ],
  "addons_repositories": []
}
```

and setup tradfri 
nothing else.
After reboot hass doesn't start, showing this:

```
core-ssh:/config# hassio homeassistant logs
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 367, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 342, in main
    args = get_arguments()
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 90, in get_arguments
    import homeassistant.config as config_util
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 26, in <module>
    from homeassistant.util.yaml import load_yaml
  File "/usr/lib/python3.6/site-packages/homeassistant/util/yaml.py", line 11, in <module>
    import keyring
  File "/usr/lib/python3.6/site-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.6/site-packages/keyring/core.py", line 14, in <module>
    from . import backend
  File "/usr/lib/python3.6/site-packages/keyring/backend.py", line 12, in <module>
    import pkg_resources
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 650, in _build_master
    ws = cls()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 643, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 699, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2023, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2432, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2772, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2397, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2565, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 185: invalid continuation byte
```

tried twice, same result... i'm not familiair with docker/hass.io.

**Comment by pvizeli** [comment]
You homeassistant config is invalid. Maybe you have a wrong char on it. Use a online yaml validator to fix it and run `hassio homeassistant check` before you reboot the system.

**Comment by koen01** [comment]
the point is that i did not change the configuration. 
clean install. only added hass.io addons...
