### ISSUE TITLE
Errors thrown to log on restart after upgrade to version 0.53 then won't restart

### ISSUE THREAD

**Issue by JSCSJSCS** [home-assistant/hassio#186]
After upgrading to Hass.io version 0.53, the following errors are logged after restart. Then I tried to restart again and it got stuck at the main screen and Home icon showing Uploading data. On a hunch, I commented out the sensor: section of the config file and it came back. I would like to get the WU sensors back online if possible.

```
2017-09-11 10:05:36 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=252 from 2017-09-11 16:52:24.443988)
2017-09-11 10:05:38 ERROR (SyncWorker_7) [homeassistant.components.sensor.wunderground] Check WUnderground API ('Expecting value: line 2 column 1 (char 1)',)
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 247, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 689, in device_state_attributes
    for (attr, callback) in attrs.items():
AttributeError: 'function' object has no attribute 'items'
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 238, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 256, in async_update_ha_state
    self._attr_setter('entity_picture', str, ATTR_ENTITY_PICTURE, attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 323, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/wunderground.py", line 712, in entity_picture
    return re.sub(r'^http://', 'https://', url, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2017-09-11 10:05:48 WARNING (MainThread) [homeassistant.setup] Setup of media_player is taking over 10 seconds.
2017-09-11 10:05:50 WARNING (MainThread) [homeassistant.setup] Setup of device_tracker is taking over 10 seconds.
2017-09-11 10:05:50 WARNING (MainThread) [homeassistant.setup] Setup of switch is taking over 10 seconds.
2017-09-11 10:05:51 WARNING (MainThread) [homeassistant.setup] Setup of tts is taking over 10 seconds.
2017-09-11 10:05:57 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform usps is taking over 10 seconds.
2017-09-11 10:05:58 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2017-09-11 10:06:16 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: Object of type 'function' is not JSON serializable
```
I have not made any changes to the Weather Underground component and the sensors do seem to be working when I look at the States page.
I may have an unusual way of implementing it though which has not been a problem until now:

I have this in my configuration.yaml file:

```
# Weather prediction
sensor: !include sensors.yaml
```
The above line is what I commented out (along with some customizations) to get Hass,io to restart. 

And this is my sensors.yaml file which worked before the 0.53 upgrade:

```
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - dewpoint_f                #  Temperature in Fahrenheit below which water droplets begin to condense and dew can form
      - feelslike_f               #  Feels like (or apparent) temperature in Fahrenheit
      - pressure_in               #  Atmospheric air pressure in inches

etc.....
```
I did not change my WU api key, but just to be sure, I did log in and compare it and it is correct.

**Comment by arsaboo** [comment]
This has already been filed https://github.com/home-assistant/home-assistant/issues/9379

Unless the bug is specific to Hassio, use the main repo to file bugs.

**Comment by JSCSJSCS** [comment]
@arsaboo , Thanks. Just for future reference, as a Hass.io only user, how does one know an issue isn't specific to Hass.io and so the requirement to post issues in main repo? Or should I just always post issues there and let the smarter people figure that out?

**Comment by arsaboo** [comment]
@JSCSJSCS IN general, it is safe to file bugs against the main repo, unless your bugs are related to Hassio configuration, access, etc.
