### ISSUE TITLE
Tradfri problem.

### ISSUE THREAD

**Issue by Warfacenl** [home-assistant/hassio#241]
I can't get to get tradfri working. I need to put my Security Code in, at the HA panel ( homepage) and it doesn't do nothing, when i check the error log i am see this message. 

`2017-11-06 23:16:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/tradfri.py", line 66, in configuration_callback
    psk = yield from api_factory.generate_psk(callback_data.get('key'))
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 193, in generate_psk
    self._psk = yield from self.request(command)
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 149, in request
    result = yield from self._execute(api_commands)
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 141, in _execute
    api_command.result = _process_output(res, parse_json)
  File "/usr/lib/python3.6/site-packages/pytradfri/command.py", line 71, in result
    self._result = self._process_result(value)
  File "/usr/lib/python3.6/site-packages/pytradfri/gateway.py", line 28, in process_result
    return result[ATTR_PSK]
TypeError: 'NoneType' object is not subscriptable`

**Comment by pvizeli** [comment]
Please ask on Home-Assistant repository. Thanks for reporting
