### ISSUE TITLE
Update to 0.57.3 failed

### ISSUE THREAD

**Issue by Fompa** [home-assistant/hassio#251]
I run an update to the new version 0.57.3 from the UI. 
The update failed and if I run hassii homeassistant check i got this information. 

Error on homeassistant/check: starting version 3.2.2
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 374, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 349, in main
    args = get_arguments()
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 90, in get_arguments
    import homeassistant.config as config_util
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 23, in <module>
    from homeassistant.core import callback, DOMAIN as CONF_CORE
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 33, in <module>
    from homeassistant import loader
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 25, in <module>
    from homeassistant.util import OrderedSet
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 17, in <module>
    from .dt import as_local, utcnow
  File "/usr/lib/python3.6/site-packages/homeassistant/util/dt.py", line 8, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

Only me with this problem? Can I solv it without a new installation?

**Comment by pvizeli** [comment]
Hardware?

**Comment by Fompa** [comment]
Raspberry PI 3 with a RaZberry2 card for Z-wave.

**Comment by pvizeli** [comment]
Any problem with 0.58.1?
