### ISSUE TITLE
hassio 0.58.1 start error........help plz

### ISSUE THREAD

**Issue by plutosherry** [home-assistant/hassio#265]
hassio 0.58.1 start error........help plz
this is the error logs:
➜  ~ hassio homeassistant logs
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 374, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 349, in main
    args = get_arguments()
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 90, in get_arguments
    import homeassistant.config as config_util
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 14, in <module>
    import voluptuous as vol
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
EOFError: marshal data too short

**Comment by pvizeli** [comment]
Make a downgrade/upgrade. I think that should fix the problem

**Comment by frenck** [comment]
@plutosherry Is the error fixed?
