### ISSUE TITLE
Custom component dependencies failing

### ISSUE THREAD

**Issue by thomaspurchas** [home-assistant/hassio#269]
I have a custom component that relies on a single pure-python dependency. It seems that hassio managed to install the dependency (I can see stuff in the `deps` directory). But every time hassio starts I see the following error, and component won't load.

The dependency in question is `gpiozero==1.4.0` and properly specified in the component.

I'm running hassio 0.59.2

```
2017-12-08 14:40:20 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform rpi_energenie
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/rpi_energenie.py", line 41, in setup_platform
    switches.append(RPiEnergenie(name, port))
  File "/config/custom_components/switch/rpi_energenie.py", line 51, in __init__
    from gpiozero import Energenie
  File "/config/deps/lib/python3.6/site-packages/gpiozero/__init__.py", line 22, in <module>
    from .devices import (
  File "/config/deps/lib/python3.6/site-packages/gpiozero/devices.py", line 480, in <module>
    Device.pin_factory = _default_pin_factory()
  File "/config/deps/lib/python3.6/site-packages/gpiozero/devices.py", line 444, in _default_pin_factory
    dist = pkg_resources.get_distribution('gpiozero')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 557, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gpiozero' distribution was not found and is required by the application
```

**Comment by borisbLL** [comment]
Hi Tom have you tried to

**Comment by thomaspurchas** [comment]
Unfortunately I'm running Hass.io so I can't apt-get.

After doing more work I've discovered that this issue resides in gpiozero. It's installing fine, but it makes heavy use of `pkg_resources` to cleverly import things depending on platform. Unfortunately its completely incompatible with the way HASS handles dependencies :(.

I've completely rewritten my custom component to remove the dependency on `gpiozero` now.

**Comment by pvizeli** [comment]
Our Image support only official components + dependencies.

But I try to write a add-on that can build python libs into deps folder. So you can use this in future for build custom python modules.

**Comment by thomaspurchas** [comment]
@pvizeli don't bother doing it for this bug, as it won't help. I've already tested other dependancies being installing into the deps folder using existing homeassistant infrastructure, and that works just fine. It's just this perticular libary that's an issue.

I'm gonna close this issue, beacue I don't think it belongs here, more an issue with how dependancies are handleded in home-assistatn.
