### ISSUE TITLE
Bluetooth problem since 0.60.1

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/hassio#307]
Version: 0.60.1
Running on RPI3
Running Hassio
Supervisor version 0.81
Host OS version 1.1

Problem is with `bluetooth_tracker`. Sample config:
```
device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
        track_new_devices: True
        hide_if_away: False
```

## Simptom:
Tracker is no longer reporting state, making all devices "Away" and in logs there is the below error repeated multiple times every 30 seconds.

```
Log Details (ERROR)
Sat Jan 13 2018 14:38:09 GMT+0200 (EET)

Error looking up Bluetooth device
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bluetooth/bluez.py", line 31, in discover_devices
    lookup_class=lookup_class, device_id=device_id)
_bluetooth.error: (110, 'Operation timed out')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 76, in update_bluetooth
    for dev in discover_devices():
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 42, in discover_devices
    lookup_class=False)
  File "/usr/lib/python3.6/site-packages/bluetooth/bluez.py", line 34, in discover_devices
    raise BluetoothError ("error communicating with local "
bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter
```

I restart complete system (host OS reboot) and home-assistant container comes up at 10:34 and 1st error is at 10:47 already. 

## What i've tried 
- Restart HostOS - no luck, error comes back
- Removing MiFlora configuration (that I've added in 0.60.1 in the hope it works) - it also caused Timer out of sync problems more often
- Restarting `Bluetooth BCM43xx` container
- Uninstalling and reinstalling `Bluetooth BCM43xx` container

Notes: any changes to bluetooth container were followed by Host OS reboot.

**Comment by pvizeli** [comment]
Try version 1.1 but look like a hardware problem.

Can you post the log of bluetooth addon?

**Comment by ciotlosm** [comment]
No logs it seems. I tried both through interface and through host:
```
root@hassio:~# docker logs addon_core_bluetooth_bcm43xx
root@hassio:~# 
```

**Comment by pvizeli** [comment]
You need click on reload on add-on store to force the store updates.

**Comment by ciotlosm** [comment]
Thank you for the help. I've used your steps and now bluetooth addon is at 1.1

`addon_core_bluetooth_bcm43xx` now showed a bit different logs on startup with no errors (there is a bug somewhere as the logs disappear in time and can't be accessed neither through docker logs <container>)

## Result after upgrade
My Bluetooth devices tracking is no longer failing as often as it previously did. It's a good improvement. 

- Previous: every 30 seconds
- Now: every 10+ minutes 

```
2018-01-14 11:19:40 DEBUG (SyncWorker_18) [homeassistant.components.device_tracker.bluetooth_tracker] Bluetooth devices discovered = 0
2018-01-14 11:19:40 DEBUG (SyncWorker_18) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:AA
2018-01-14 11:19:41 DEBUG (SyncWorker_18) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:BB
2018-01-14 11:19:42 INFO (SyncWorker_3) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:19:43 INFO (SyncWorker_3) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:19:55 INFO (SyncWorker_12) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:19:59 INFO (SyncWorker_12) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:20:03 DEBUG (SyncWorker_9) [homeassistant.components.device_tracker.bluetooth_tracker] Bluetooth devices discovered = 0
2018-01-14 11:20:03 DEBUG (SyncWorker_9) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:AA
2018-01-14 11:20:04 DEBUG (SyncWorker_9) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:BB
2018-01-14 11:20:08 INFO (SyncWorker_10) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:20:13 INFO (SyncWorker_10) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:20:21 INFO (SyncWorker_8) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:20:22 INFO (SyncWorker_8) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:20:34 INFO (SyncWorker_2) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:20:35 INFO (SyncWorker_2) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:20:38 ERROR (SyncWorker_4) [homeassistant.components.device_tracker.bluetooth_tracker] Error looking up Bluetooth device
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bluetooth/bluez.py", line 31, in discover_devices
    lookup_class=lookup_class, device_id=device_id)
_bluetooth.error: (110, 'Operation timed out')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 76, in update_bluetooth
    for dev in discover_devices():
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 42, in discover_devices
    lookup_class=False)
  File "/usr/lib/python3.6/site-packages/bluetooth/bluez.py", line 34, in discover_devices
    raise BluetoothError ("error communicating with local "
bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter
2018-01-14 11:20:47 INFO (SyncWorker_1) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:20:48 INFO (SyncWorker_1) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:21:00 INFO (SyncWorker_11) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:21:01 DEBUG (SyncWorker_18) [homeassistant.components.device_tracker.bluetooth_tracker] Bluetooth devices discovered = 0
2018-01-14 11:21:01 DEBUG (SyncWorker_18) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:AA
2018-01-14 11:21:02 DEBUG (SyncWorker_18) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:BB
2018-01-14 11:21:03 INFO (SyncWorker_11) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:21:13 INFO (SyncWorker_16) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:21:16 INFO (SyncWorker_16) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:21:25 DEBUG (SyncWorker_12) [homeassistant.components.device_tracker.bluetooth_tracker] Bluetooth devices discovered = 0
2018-01-14 11:21:25 DEBUG (SyncWorker_12) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:AA
2018-01-14 11:21:26 INFO (SyncWorker_16) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:21:26 DEBUG (SyncWorker_12) [homeassistant.components.device_tracker.bluetooth_tracker] Scanning AA:AA:AA:AA:AA:BB
2018-01-14 11:21:29 INFO (SyncWorker_16) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
2018-01-14 11:21:39 INFO (SyncWorker_8) [homeassistant.components.device_tracker.nmap_tracker] Scanning...
2018-01-14 11:21:42 INFO (SyncWorker_8) [homeassistant.components.device_tracker.nmap_tracker] nmap scan successful
```

![screen shot 2018-01-14 at 11 30 57](https://user-images.githubusercontent.com/7738048/34914610-7b6c66f6-f91e-11e7-98a8-4bb734bd725d.png)

**Comment by ciotlosm** [comment]
Trying a complete COLD reboot

**Comment by pvizeli** [comment]
I think that could be a hardware problem with your SoC.

The problem is, if you use the bluetooth from SoC, the chip use a lot of resource from CPU for this and the OS lost this and failing into resource problems.

I hope the next raspberry will have a external bluetooth chip or don't share resource with other chips and CPU on his SoC. Actual the bluetooth chip slow done the rpi in a heavy way.

**Comment by ciotlosm** [comment]
I understand. The weird thing is that this was never a problem in the same setup previously. I wish there was a better way to have bluetooth (and even bluetooth LE) outside of the pi. 

If you have any suggestion on external setup, I'd love to try it.

**Comment by ciotlosm** [comment]
@pvizeli I've also added a CPU graph for a longer period for my Hass.io. It seems we've been getting increases in CPU usage over time:

![screen shot 2018-01-15 at 09 29 01](https://user-images.githubusercontent.com/7738048/34931185-08721174-f9d6-11e7-9450-8aa05e96c247.png)

**Comment by ciotlosm** [comment]
Latest build doesn't complete platform setup:

```
2018-01-16 09:38:04 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform bluetooth_tracker
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bluetooth/bluez.py", line 31, in discover_devices
    lookup_class=lookup_class, device_id=device_id)
_bluetooth.error: (110, 'Operation timed out')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 169, in async_setup_platform
    disc_info)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 65, in setup_scanner
    for dev in discover_devices():
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 43, in discover_devices
    lookup_class=False)
  File "/usr/lib/python3.6/site-packages/bluetooth/bluez.py", line 34, in discover_devices
    raise BluetoothError ("error communicating with local "
bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter
```

**Comment by ciotlosm** [comment]
I will close this issue and assume a hardware problem with my raspberry pi until I get a chance to test different hardware.
