### ISSUE TITLE
hass io setup failed

### ISSUE THREAD

**Issue by Z-pi** [home-assistant/hassio#316]
hass io is unable to setup when launching home assistant. 
`2018-01-16 00:39:39 ERROR (MainThread) [homeassistant.setup] Error during setup of component hassio
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 196, in _async_setup_component
    result = yield from component.async_setup(hass, processed_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hassio.py", line 172, in async_setup
    if not (yield from hassio.is_connected()):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hassio.py", line 262, in _wrapper
    data = yield from funct(*argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hassio.py", line 333, in send_command
    X_HASSIO: os.environ.get('HASSIO_TOKEN')
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 99, in __iter__
    ret = yield from self._coro
  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 275, in _request
    resp = req.send(conn)
  File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 463, in send
    writer.write_headers(status_line, self.headers)
  File "/usr/lib/python3.6/site-packages/aiohttp/http_writer.py", line 247, in write_headers
    [k + SEP + v + END for k, v in headers.items()])
  File "/usr/lib/python3.6/site-packages/aiohttp/http_writer.py", line 247, in <listcomp>
    [k + SEP + v + END for k, v in headers.items()])
TypeError: must be str, not NoneType` 

i'm on 0.61

**Comment by cogneato** [comment]
Same error here after update to .61

**Comment by pvizeli** [comment]
Fix with supervisor 0.82
