### ISSUE TITLE
Zigbee Bulbs no longer working

### ISSUE THREAD

**Issue by psalmx89** [home-assistant/hassio#318]
.61 zha bellows component introduced a bug in zigbee light support.  Bulbs that are not RGB will no longer appear in home assistant.  See home assistant pull request #11670

**Comment by sumitrajancse** [comment]
I have a lightify RBG zigbee protocol bulb . It only appear as normal bulb with color temperature .it never worked as color bulb with any version. 
Which bulb are you using?

**Comment by psalmx89** [comment]
Same lightify RGB bulb. .61 adds support for color wheel, but now my GE link are now longer showing as entities.  Still appear in zigbee.db  Error log attached. 

raceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/light/zha.py", line 46, in async_setup_platform
    endpoint.light_color, ['color_temperature'])
  File "/usr/lib/python3.6/site-packages/bellows/zigbee/endpoint.py", line 143, in __getattr__
    raise AttributeError
AttributeError
2018-01-16 18:21:08 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform zha
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bellows/zigbee/endpoint.py", line 141, in __getattr__
    return self._cluster_attr[name]
KeyError: 'light_color'

**Comment by pvizeli** [comment]
Please report this on Home-Assistant. Thanks for contribute
