### ISSUE TITLE
Local add-ons broken in 0.8.6 and 0.8.7

### ISSUE THREAD

**Issue by neffs** [home-assistant/hassio#351]
```
18-02-09 23:41:17 INFO (SyncWorker_16) [hassio.docker.addon] Start build local/armhf-addon-hello_world:1
18-02-09 23:41:27 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/hassio/api/security.py", line 34, in security_layer
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/utils.py", line 33, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 554, in install
    if not await self.instance.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/docker/utils.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/docker/addon.py", line 259, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/docker/addon.py", line 274, in _build
    image.tag(self.image, tag='latest')
AttributeError: 'tuple' object has no attribute 'tag'

```

**Comment by mcolyer** [comment]
I too have this problem.

**Comment by snozzlebert** [comment]
Probably related to this change: https://github.com/docker/docker-py/commit/631cc3c1215441edb075a999a77061c1275c5e5a#diff-09601dc06f827854235b699fb754ecb8

**Comment by mcolyer** [comment]
Is there a way to downgrade? I tried post 0.85 to the /supervisor/upgrade
endpoint without success.

**Comment by pvizeli** [comment]
Yes, on a productive system you can only move forward. So a PR that fix the issue is the fast way.
In development mode you can spring around with version but a lot of things that you want use, don't work in dev mode. I will look to this in 1-2 hours and make a release. help are welcome. Thanks for the link
