### ISSUE TITLE
zigbee issues after update

### ISSUE THREAD

**Issue by jeubanks** [home-assistant/hassio#383]
The ZHA component is now failing to start after update to 0.64

----------------
Mon Feb 26 2018 09:58:15 GMT-0500 (EST)

Error during setup of component zha
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    result = yield from component.async_setup(hass, processed_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/zha/__init__.py", line 96, in async_setup
    from bellows.zigbee.application import ControllerApplication
  File "/usr/lib/python3.6/site-packages/bellows/zigbee/application.py", line 7, in <module>
    import zigpy.application
  File "/usr/lib/python3.6/site-packages/zigpy/application.py", line 6, in <module>
    import zigpy.appdb
  File "/usr/lib/python3.6/site-packages/zigpy/appdb.py", line 4, in <module>
    import zigpy.device
  File "/usr/lib/python3.6/site-packages/zigpy/device.py", line 5, in <module>
    import zigpy.endpoint
  File "/usr/lib/python3.6/site-packages/zigpy/endpoint.py", line 7, in <module>
    import zigpy.util
  File "/usr/lib/python3.6/site-packages/zigpy/util.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 3, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 32, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'

**Comment by PhilRW** [comment]
Same here. See [this issue](https://github.com/home-assistant/home-assistant/issues/12675). I tried pip3 steps as a workaround but unfortunately there appears to be no gcc installed in the hassio docker image.

**Comment by pvizeli** [comment]
I close that issue on hassio while it is a home-assistant problem
