### ISSUE TITLE
Telegram-bot component / notify.telegram not working in 0.64

### ISSUE THREAD

**Issue by HomeGuy** [home-assistant/hassio#392]
Hass.io version: 0.64

Hass.io Supervisor version 0.95

Component: Telegram-bot

Description of problem: Telegram-bot component used [broadcast-only](https://home-assistant.io/components/telegram_bot.broadcast/) no longer functions after updating from 0.63.3 to 0.64. No configuration changes were made in between. Result: This bricks telegram bot notification messages used in automations.

Expected: Normal telegram-bot functionality after update

Additional info from home-assistant.log:
> 2018-02-26 23:35:03 WARNING (SyncWorker_0) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)",)': /bot***/getMe
2018-02-26 23:35:09 WARNING (SyncWorker_0) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)",)': /bot***/getMe
2018-02-26 23:35:14 WARNING (SyncWorker_0) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)",)': /bot***/getMe
2018-02-26 23:35:19 ERROR (MainThread) [homeassistant.components.telegram_bot] Error setting up platform broadcast
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "(removed quotation symbols for legilibility)string", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 190, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot***/getMe (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)",))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/telegram_bot/__init__.py", line 230, in async_setup
    platform.async_setup_platform(hass, p_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/telegram_bot/broadcast.py", line 25, in async_setup_platform
    bot_config = yield from hass.async_add_job(bot.getMe)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 191, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 240, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 196, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot***/getMe (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)",))
2018-02-26 23:35:19 ERROR (MainThread) [homeassistant.setup] Setup failed for telegram_bot: Component failed to initialize.
2018-02-26 23:35:19 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of notify.telegram. Setup failed for dependencies: telegram_bot
2018-02-26 23:35:19 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform notify.telegram: Could not setup all dependencies.

> 

Hopefully anyone can help :-)

**Comment by disrupted** [comment]
seeing a lot of issues with `telegram_bot` component as well since upgrading to 0.64, especially repeating triggers every minute. there's a post about it on the community forums. https://community.home-assistant.io/t/telegram-text-event-dont-stop-triggering/45067 and the correspondent issue: https://github.com/home-assistant/home-assistant/issues/12774

**Comment by pvizeli** [comment]
I close this, while it is a home-assistant bug 👍 Thanks for reporting
