### ISSUE TITLE
cpuspeed Sensor Crashes on Update

### ISSUE THREAD

**Issue by xanderrobar** [home-assistant/hassio#398]
Running Hassio on an Raspberry Pi 3 B with the following versions:

- Hass.io supervisor: 0.96
- Host system: 1.2
- Home Assistant: 0.64.3

The following error occurs when trying to use the cpuspeed sensor platform:

```
2018-03-04 11:59:43 ERROR (MainThread) [homeassistant.components.sensor] cpuspeed: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 197, in _async_add_entity
    yield from entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/cpuspeed.py", line 86, in update
    self._state = round(float(self.info['hz_actual_raw'][0])/10**9, 2)
KeyError: 'hz_actual_raw'
```

My sensor setup is very basic:
```
sensor:
  - platform: cpuspeed
```

Bug [#9809](https://github.com/home-assistant/home-assistant/issues/9809) on the home-assistant project indicates this is a problem specific to Hassio, as the sensor works fine on the same hardware running Hassbian.

**Comment by tenkaibr** [comment]
Same here on Home Assistant 0.72.1

**Comment by TheCellMC** [comment]
Same here on HA 0.75.1

**Comment by claesr** [comment]
Same here on HA 0.77.2

**Comment by ferdydek** [comment]
Same on HA (hassio) 0.79.2
