### ISSUE TITLE
Interface conversion: interface is nil, not string

### ISSUE THREAD

**Issue by sjorsjes** [home-assistant/hassio#449]
**Home Assistant release with the issue:**
```
{
    "result": "ok",
    "data": {
        "version": "0.66.1",
        "last_version": "0.67.0",
        "image": "homeassistant/raspberrypi3-homeassistant",
        "custom": false,
        "boot": true,
        "port": 8123,
        "ssl": true,
        "watchdog": true,
        "wait_boot": 600
    }
}
```

**Last working Home Assistant release (if known):**
0.65

**Operating environment (Hass.io/Docker/Windows/etc.):**
Raspberry PI 3 with Hass.io

**Component/platform:**
x

**Description of problem:**
Since version 0.66 I received many `Error doing job: Task was destroyed but it is pending!` errors but everything seemed to be working like it should except for the hassio specific config pages. I tried to update to 0.67 through the hassio command line, but then i recieve `Interface conversion: interface is nil, not string`  error (see full error below). I disabled all components so only some basic things from HA are running.

**Additional information:**
```
core-ssh:~# hassio homeassistant update
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2c5f60, 0x107b4400)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107c0200, 0x24, 0x200, 0x0)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f5e63, 0xd, 0x7ec1ae5a, 0x6, 0x0, 0x0, 0x76000, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x10780420)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2ae6d8, 0x323754, 0x10780420, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f5e63, 0xd, 0x0, 0x0, 0x409d10, 0x1, 0x1, 0x300cfa, 0x2f, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x1076c8c0, 0x1070a180, 0x3, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
```

* [Full home assistant logs](https://gist.github.com/sjorsjes/dd890fa912b910c0e69a0c25e7e79284)

**Comment by bdimir** [comment]
Same issue here. I have downgraded to 66.1 and still the same. I used different SD card in case previous SD is corrupted. Any clues?

**Comment by det-peralta** [comment]
+1 

So what can i do now? i cant access my hassio web interface.

**Comment by det-peralta** [comment]
This fix my problem.

<a class="embedly-card" href="https://www.reddit.com/r/homeassistant/comments/8chb07/hassio_interface_conversion_interface_is_nil_not/dxgy7j1">Card</a>
<script async src="//embed.redditmedia.com/widgets/platform.js" charset="UTF-8"></script>

**Comment by det-peralta** [comment]
After a while the error presists.

**Comment by prigal** [comment]
Same problem here.

**Comment by MikePT28** [comment]
I also have this problem.
```
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2c7050, 0x1070a780)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107ee000, 0x24, 0x200, 0x0)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f6f83, 0xd, 0x7ef25e5d, 0x6, 0x0, 0x0, 0x76500, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x1078e420)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2af768, 0x324b14, 0x1078e420, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f6f83, 0xd, 0x0, 0x0, 0x40bd10, 0x1, 0x1, 0x301e4d, 0x2f, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107ba380, 0x1070a160, 0x3, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
```

**Comment by vongomben** [comment]
same on Hassio 0.70, but is the IP given to your pi "normal"? 
Mine was given a strange ip if I run ifconfig from ssh (note I logged in on the normal ip address). I guess (at least in my case) home assistant is active on that istance, not accessible to me though.

**Comment by simonszu** [comment]
@vongomben Yes, it is quite normal that this IP isn't your external IP you connect via SSH to. HassIO is based on docker, which has its own internal network management, so you are basically connecting to the plain OS on your pi, and then get instantly forwarded into the docker container HassIO is running from. 

If you mount the SD card which is in your pi on another (linux) computer, you will notice that the directory layout isn't the one you are used to when browsing the filesystem via SSH - it's the same reason behind it. 

Home Assistant is active on that interface, and has the internal 172.xxx IP, yes, but the Host OS from where the docker container is executed, translates the traffic to the outside, say, your home network transparently, so it should be no general issue. I suppose the HassIO maintainers are aware of their own docker layout and consider it into the hassio binary ;)

**Comment by ciotlosm** [comment]
I was able to reproduce the error in the first post by making a change in configuration.yaml that was invalid and home assistant would not start. Then I fixed the problem in configuration and tried to use hassio CLI to start home assistant (hassio ha start) andI got the error.

**Comment by Burnett2k** [comment]
having the same `interface is nil` problem after modifying some configs. I then reverted all of them and am sure they are now valid again (because I use git and it shows no modifications to the files).  If anyone knows how to get things back up and running please let me know! This is the first time my HASS has been inoperable for over a day and it is depressing =(

**Comment by ciotlosm** [comment]
@Burnett2k cold reboot of whole system should work

**Comment by ciotlosm** [comment]
For future reference: The community SSH addon has a bit better results with hassio CLI. 
For easier troubleshoot, when showing stacktrace of future errors, when running the command use also `-d` flag:
```
hassio -d ha stop
```

**Comment by Burnett2k** [comment]
I have powered down my rpi3 multiple times and can't get the UI up and running again.  @ciotlosm 
```
DEBUG [CmdHomeassistant]: action->'stop', endpoint='stop', serverOverride->'', GET->'false', options->'', rawjson->'false', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'stop', serverOverride->'', get->'false', Options->'', Filter->'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'stop', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/stop', GET->'false', payload->''
DEBUG [RestCall]: ResponseBody->'{"result": "error", "message": null}'
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2c5f60, 0x107de200)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107f0000, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f5e63, 0xd, 0x7ea13e64, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x107864d0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2ae6d8, 0x323754, 0x107864d0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f5e63, 0xd, 0x0, 0x0, 0x409d10, 0x1, 0x1, 0x300cfa, 0x2f, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107b2380, 0x1070a160, 0x4, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
```

**Comment by ciotlosm** [comment]
@Burnett2k what does `hassio ha logs` show? where does it get stuck? Are you sure you don't have a config problem? A reboot would have forced a start on the container. If config was fine you should have seen a restore regardless of CLI problems.

**Comment by Burnett2k** [comment]
@ciotlosm I stored my last working configs in git, so I'm confident no configuration files are having issues. 

Here is the output of `hassio ha logs`
```
Error decoding json invalid character 'T' looking for beginning of value: Traceb                                   ack (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 377, i                                   n <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 352, i                                   n main
    args = get_arguments()
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 85, in                                    get_arguments
    import homeassistant.config as config_util
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 15, in <                                   module>
    from homeassistant import auth
  File "/usr/lib/python3.6/site-packages/homeassistant/auth.py", line 15, in <mo                                   dule>
    from homeassistant import data_entry_flow, requirements
  File "/usr/lib/python3.6/site-packages/homeassistant/requirements.py", line 7,                                    in <module>
    import homeassistant.util.package as pkg_util
  File "/usr/lib/python3.6/site-packages/homeassistant/util/package.py", line 12                                   , in <module>
    import pkg_resources
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017,                                    in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003,                                    in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030,                                    in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 650, i                                   n _build_master
    ws = cls()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 643, i                                   n __init__
    self.add_entry(entry)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 699, i                                   n add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2023,                                    in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2432,                                    in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2772,                                    in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2397,                                    in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2565,                                    in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471,                                    in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1468,                                    in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 108: invali                                   d start byte
```

**Comment by ryanm101** [comment]
sorry didnt see this as i typically only watch hassio-cli for issues. 
I'll take a look this weekend

**Comment by ryanm101** [comment]
Anyone having Issues please include:

`hassio --version`

`hassio -d <yourcommand>` output

and the command run.

**Comment by MosquitoD4K** [comment]
```
core-ssh:~# hassio host reboot
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2c7050, 0x107ac3c0)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107b6200, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f45fc, 0x4, 0x7edd5e62, 0x6, 0x0, 0x0, 0x76500, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHost(0x107784d0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/host.go:42 +0x4f0
github.com/urfave/cli.HandleAction(0x2af768, 0x324b18, 0x107784d0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f45fc, 0x4, 0x0, 0x0, 0x40bd20, 0x1, 0x1, 0x2fabdf, 0x18, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107648c0, 0x1070a120, 0x3, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
```


```
core-ssh:~# hassio --version
hassio version 1.3.1
```

```
core-ssh:~# hassio ha info
{
    "result": "ok",
    "data": {
        "version": "0.70.1",
        "last_version": "0.70.1",
        "machine": "raspberrypi3",
        "image": "homeassistant/raspberrypi3-homeassistant",
        "custom": false,
        "boot": true,
        "port": 8123,
        "ssl": false,
        "watchdog": true,
        "wait_boot": 600
    }
}

```

**Comment by ryanm101** [comment]
Notes for me:
Reference: https://github.com/home-assistant/hassio/blob/dev/API.md

```
 ~ curl -s -X POST -H "X-HASSIO-KEY: $HASSIO_TOKEN" http://hassio/host/reboot
{"result": "error", "message": null}#                                                                                                                                           ➜  ~ curl  -X POST -H "X-HASSIO-KEY: $HASSIO_TOKEN" http://hassio/host/reboot 
{"result": "error", "message": null}#                                                                                                                                           ➜  ~ curl  -X GET -H "X-HASSIO-KEY: $HASSIO_TOKEN" http://hassio/host/info
{"result": "ok", "data": {"chassis": null, "version": null, "last_version": null, "type": null, "features": [], "hostname": null, "operating_system": null, "deployment": null, "kernel": null}}#            
```

**Comment by riker09** [comment]
I ~~am~~ was affected:

```bash
core-ssh:~# hassio --version
hassio version 1.3.1```

```bash
core-ssh:~# hassio ha start
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2c7050, 0x107ac440)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107b8200, 0x24, 0x200, 0x0)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f6f83, 0xd, 0x7ee95e58, 0x5, 0x0, 0x0, 0x76500, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x10778420)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2af768, 0x324b14, 0x10778420, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f6f83, 0xd, 0x0, 0x0, 0x40bd10, 0x1, 0x1, 0x301e4d, 0x2f, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107648c0, 0x1070a140, 0x3, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
````

Then I removed the last addon I installed, Pi-Hole (`hassio ad uninstall --name a0d7b954_pi-hole`). After a some minutes the system was starting again with `hassio ha start`. I *think* between issuing the uninstall command and the successful start I've witnessed the error, but I'm not 100% sure on this.

**Comment by Burnett2k** [comment]
I will leave an update here as well.  After trying many things I ended up totally reinstalling HASSIO on my rpi3. Luckily, I backed everything up to Git.

It does not appear that I had a bad configuration file or anything like that, but something happened which put HASS in such a bad state that it wouldn't even run the UI and wouldn't honor any CLI commands... It was a pain to fix everything, but now I realize I need a better backup / restore procedure so I'm not down for days next time.

**Comment by Dracoy** [comment]
@Burnett2k Did you have to reformat SD card? I'm having trouble reformating SD card to resinstall HASSIO. Similar problems here.

**Comment by pvizeli** [comment]
use `hassio su logs` and you see was going on. I think there is a other job pending on home-assistant container and you need wait until they is done.

**Comment by Burnett2k** [comment]
@Dracoy I don't believe I reformatted the card. If I remember correctly I just used etcher to put a new version on the card and everything worked fine after that. Haven't had any problems for the past month or so.

**Comment by riker09** [comment]
@pvizeli Yes, I believe I can confirm that. I was restarting HA via the web interface but got a little bit impatiant. I tried restarting via CLI and got the "interface is nil" error. A few moments later HA was fully restarted and everything was back to normal.

I *did* have the nil error before, but much worse (as described by other people in this issue: Restarting was impossible, etc.). After I re-installed Hass.io on my SD card everything was fine and when I had that nil error yesterday I was close to another little heart attack. So I'm leaving my experience here for other people.

What would be super cool is if the developers could implement some sort of checking logic that notifies on the CLI when there is another process running instead of throwing such a crude error message.

**Comment by hank** [comment]
This happened to me when I'd dorked my config up good using the git addon (which deleted my initial config). I rebuilt it from the default config I found attached to a thread, and it seems to have fixed it.
