### ISSUE TITLE
hass.io supervisor version number

### ISSUE THREAD

**Issue by khan3962** [home-assistant/hassio#461]
Latest beta version of the hass.io supervisor is 103 instead of 0.103 making appdaemon not start because it doesn't follow the versioning syntax. Latest non beta is 0.102

Version 103 is not a valid version.Error: "No Major.Minor.Patch elements found"FATAL: You Supervisor version is: 103
FATAL: This add-on requires: >=0.85.0

**Comment by pvizeli** [comment]
CC @frenck

**Comment by colinerd** [comment]
I have the same issue - is there a workaround?
Addons are now not starting.....

**Comment by khan3962** [comment]
As a temporary workaround I left the beta channel to stay on 0.102.  Seems 103 has been made non-beta because it updated as I was at work.  Now I have no way to make it work.  Please fix soon.

**Comment by khan3962** [comment]
Version has changed to 103.1 but appdaemon is still broken. (Should be 0.103.1)
I'm getting this in the logs repeatedly: 
2018-05-05 18:18:27.708683 INFO AppDaemon: HASS: Connected to Home Assistant 0.68.1
2018-05-05 18:18:27.759253 WARNING AppDaemon: HASS: Error getting metadata
2018-05-05 18:18:27.762879 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds

**Comment by colinerd** [comment]
I was able to start the "homebridge" add-on on 103.1 however I get this error and not sure where it is coming from, config was fine prior to the update to 103;

[2018-5-6 00:55:49] Loading 0 accessories...
[2018-5-6 00:55:49] [HomeWizard] Listening UDP IPv4 0.0.0.0:33333
[2018-5-6 00:55:49] [HomeWizard] Listening HTTP:8087
[2018-5-6 00:55:49] [HomeWizard] Running : homebridge-homewizard 0.0.59
undefined:1
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
^
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-homeassistant/index.js:101:38)
    at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by frenck** [comment]
This issue has been fixed upstream in the Supervisor. Release 103.2 fixes it.

To upgrade:

![](http://g.recordit.co/ZbO5PRMkn1.gif)
