### ISSUE TITLE
Error importing module for Leviton Decora Wi-fi component

### ISSUE THREAD

**Issue by rkpatel33** [home-assistant/hassio#475]
This is what my logs say, is there any way to install this manually by ssh'ing in, or does this just need to be fixed in the next release?

```
2018-05-15 22:47:04 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform decora_wifi
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/light/decora_wifi.py", line 40, in setup_platform
    from decora_wifi import DecoraWiFiSession
ModuleNotFoundError: No module named 'decora_wifi'
2018-05-15 22:47:19 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
```

**Comment by pvizeli** [comment]
Will be in next build: https://github.com/home-assistant/hassio-build/commit/2c0f176b63934de62e2ef5b4c7b14ca40f0eb87e

**Comment by rkpatel33** [comment]
Thanks, any estimate on when that will be?
