### ISSUE TITLE
pollen.com setup fails, KeyError: 'allergy_index'

### ISSUE THREAD

**Issue by gorobotgo** [home-assistant/hassio#563]
environment: hass.io
first release with issue: 0.73.0
last working release: unknown
component: pollen

Pollen.com setup fails with errors, entities specified for monitoring (allergy_index_today, disease_average_forecasted) are not listed on states screen. An unexpected entity, "sensor.cold__flu_forecasted_average_2", is listed on states screen, despite not being a valid entity according to the component documentation.

Traceback:

    2018-07-08 13:00:53 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.pollen
    2018-07-08 13:00:53 ERROR (MainThread) [homeassistant.components.sensor] pollen: Error on device update!
    Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
    File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 317, in async_device_update
    yield from self.async_update()
    File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/pollen.py", line 186, in async_update
    data = self.pollencom.data[self._category]['Location']
    KeyError: 'allergy_index'

configuration.yaml entry:

    sensor:
      - platform: pollen
        zip_code: "27513"
        monitored_conditions:
          - allergy_index_today
          - disease_average_forecasted

It's worth noting that the 0.73 release notes seem to imply some config changes for this component, but the current component documentation seems to indicate that this config is valid.

**Comment by arsaboo** [comment]
`sensor.cold__flu_forecasted_average_2` is the entity corresponding `disease_average_forecasted`. I am also not sure why it adds `_2` to the entity name. 

Try removing the `allergy_index_today` from the `monitored_conditions`.
