### ISSUE TITLE
TasmoAdmin can not be uninstalled

### ISSUE THREAD

**Issue by omgnvq** [home-assistant/hassio#568]
As another user has noted [here](https://community.home-assistant.io/t/unable-to-uninstall-addon-tasmoadmin/59100) the addon TasmoAdmin cannot be uninstalled. @frenck from discord finds this to be a hassio issue based upon the error. 

My error is slightly different but seems fundamentally similar

```18-07-14 17:28:32 INFO (MainThread) [hassio.addons.addon] Remove Home-Assistant addon data folder /data/addons/data/a0d7b954_sonweb
18-07-14 17:28:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/security.py", line 56, in token_validation
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/utils.py", line 33, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/utils.py", line 33, in wrap_check
    return await method(addon, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 639, in uninstall
    shutil.rmtree(str(self.path_data))
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'MyConfig.php'```

**Comment by frenck** [comment]
Some add-on containers (or software running in the containers) require specific file permissions, which are set.

Supervisor seems to have an issue with this upon add-on removal or taking snapshots.

**Comment by frenck** [comment]
I've been able to reproduce this using Octobox on HassOS 1.5 as well:

```text
18-07-14 16:39:18 INFO (SyncWorker_10) [hassio.docker.interface] Remove docker hassioaddons/octobox with latest and None
18-07-14 16:39:18 INFO (MainThread) [hassio.addons.addon] Remove Home-Assistant addon data folder /data/addons/data/40817795_octobox
18-07-14 16:39:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/security.py", line 56, in token_validation
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/utils.py", line 33, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/utils.py", line 33, in wrap_check
    return await method(addon, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 639, in uninstall
    shutil.rmtree(str(self.path_data))
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 414, in _rmtree_safe_fd
    onerror(os.open, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 412, in _rmtree_safe_fd
    dirfd = os.open(name, os.O_RDONLY, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'postgres'
```

**Comment by pvizeli** [comment]
Strange, we are root. Anyway we should catch the error, maybe there are a better remove routine inside shutil.
