### ISSUE TITLE
snapshot feature does not reliably work for mariadb addon

### ISSUE THREAD

**Issue by mgolisch** [home-assistant/hassio#583]
When restoring a snapshot the data files for mariadb seem to be broken.
i think i worked before, but that might have been luck.
I asume it just saves the files from the addons data directory, which might be a bad thing to do for a database.

**Comment by pxpto** [comment]
Same problem here while moving to HassOS 1.7.

HA 0.70.1

My "core_mariadb.tar" inside the snapshot is 1,7 GB. Could that have any influence in the proccess?

```
18-07-26 13:08:36 INFO (MainThread) [hassio.snapshots] Partial-Restore 646cf599 start
18-07-26 13:08:59 INFO (MainThread) [hassio.snapshots] Restore 646cf599 old add-ons
18-07-26 13:13:49 INFO (MainThread) [hassio.addons.addon] Restore config for addon core_mariadb
18-07-26 13:13:49 INFO (MainThread) [hassio.addons.addon] Restore image for addon core_mariadb
18-07-26 13:13:49 INFO (SyncWorker_17) [hassio.docker.interface] Pull image homeassistant/armhf-addon-mariadb tag 0.2.
18-07-26 13:15:12 INFO (SyncWorker_17) [hassio.docker.interface] Tag image homeassistant/armhf-addon-mariadb with version 0.2 as latest
18-07-26 13:15:13 INFO (MainThread) [hassio.addons.addon] Restore data for addon core_mariadb
18-07-26 13:21:04 INFO (SyncWorker_15) [hassio.docker.addon] Start docker addon homeassistant/armhf-addon-mariadb with version 0.2
18-07-26 13:21:05 ERROR (MainThread) [hassio.snapshots] Restore 646cf599 error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hassio/snapshots/__init__.py", line 330, in do_restore_partial
    await self.sys_homeassistant.start()
  File "/usr/local/lib/python3.7/site-packages/hassio/utils/__init__.py", line 25, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/homeassistant.py", line 278, in _start
    raise HomeAssistantError()
hassio.exceptions.HomeAssistantError
```
