### ISSUE TITLE
Problems with wake on lan

### ISSUE THREAD

**Issue by mshrem** [home-assistant/hassio#649]
Home Assistant release with the issue:
0.75.3

Last working Home Assistant release (if known):
Dont know just got started with hassio it is my first install

Operating environment (Hass.io/Docker/Windows/etc.):
Hassio
Running on docker ubuntu 18.04 desktop or server doesnt matter both show the same problem
Component/platform:

Wake On LAN
https://www.home-assistant.io/components/switch.wake_on_lan/

Description of problem:
Wake on Lan functionality is not working properly. The following error can be seen in the logs:

`Error executing service <ServiceCall switch.turn_on (c:44c6786829bf423f8e61f844b1608915): entity_id=['switch.windowsmarcos']>
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1115, in _event_to_service_call
await service_handler.func(service_call)
File "/usr/local/lib/python3.6/site-packages/homeassistant/components/switch/init.py", line 109, in async_handle_switch_service
await switch.async_turn_on()
File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.6/site-packages/homeassistant/components/switch/wake_on_lan.py", line 87, in turn_on
self._wol.send_magic_packet(self._mac_address)
File "/usr/local/lib/python3.6/site-packages/wakeonlan.py", line 74, in send_magic_packet
packet = create_magic_packet(mac)
File "/usr/local/lib/python3.6/site-packages/wakeonlan.py", line 46, in create_magic_packet
send_data += struct.pack(b'B', int(data[i: i + 2], 16))
ValueError: invalid literal for int() with base 16: b'OA'`

**Comment by pvizeli** [comment]
I think you should ask on wakeonlan python package repository

**Comment by mshrem** [comment]
Ohhh i cant believe it ... i had a typo on the mac address problem solved.....

**Comment by IvoryAguado** [comment]
How is it working for you, I have made a fresh Hassio Install and python is unable to find the package net rpc, I guess because is in a Docker container, because the actual Rpi3b+ has it and works manually, any clue in this? thank you
