### ISSUE TITLE
Unable to uninstall addon (Google Assistant Webserver )

### ISSUE THREAD

**Issue by velijv** [home-assistant/hassio#694]
Addon in question: https://github.com/AndBobsYourUncle/hassio-addons/ (Google Assistant Webserver )

Clicking **uninstall** redirects to addons list, with the addon still remaining installed. 

Attempting to uninstall it using ssh command line `hassio addons uninstall -name “fe49a976_google_assistant_webserver”` results in:
`Error decoding json invalid character '<' looking for beginning of value: <html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>`

**Comment by pvizeli** [comment]
Can you post the supervisor logs?

**Comment by velijv** [comment]
```
Error decoding json invalid character 'r' looking for beginning of value:     return await method(addon, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 664, in uninstall
    if not await self.instance.remove():
  File "/usr/local/lib/python3.7/site-packages/hassio/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 204, in _remove
    "Remove docker %s with latest and %s", self.image, self.version)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/addon.py", line 48, in version
    return super().version
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 45, in version
    if self._meta and LABEL_VERSION in self._meta['Config']['Labels']:
TypeError: argument of type 'NoneType' is not iterable
18-09-12 06:59:25 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 83, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/utils.py", line 76, in wrap_check
    return await method(addon, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 664, in uninstall
    if not await self.instance.remove():
  File "/usr/local/lib/python3.7/site-packages/hassio/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 204, in _remove
    "Remove docker %s with latest and %s", self.image, self.version)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/addon.py", line 48, in version
    return super().version
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 45, in version
    if self._meta and LABEL_VERSION in self._meta['Config']['Labels']:
TypeError: argument of type 'NoneType' is not iterable
18-09-12 07:01:51 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
18-09-12 07:04:43 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
18-09-12 07:05:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 83, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/utils.py", line 76, in wrap_check
    return await method(addon, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 664, in uninstall
    if not await self.instance.remove():
  File "/usr/local/lib/python3.7/site-packages/hassio/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 204, in _remove
    "Remove docker %s with latest and %s", self.image, self.version)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/addon.py", line 48, in version
    return super().version
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 45, in version
    if self._meta and LABEL_VERSION in self._meta['Config']['Labels']:
TypeError: argument of type 'NoneType' is not iterable
18-09-12 07:05:20 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
18-09-12 07:05:41 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
18-09-12 07:06:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 83, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/utils.py", line 76, in wrap_check
    return await method(addon, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 664, in uninstall
    if not await self.instance.remove():
  File "/usr/local/lib/python3.7/site-packages/hassio/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 204, in _remove
    "Remove docker %s with latest and %s", self.image, self.version)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/addon.py", line 48, in version
    return super().version
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 45, in version
    if self._meta and LABEL_VERSION in self._meta['Config']['Labels']:
TypeError: argument of type 'NoneType' is not iterable
18-09-12 07:06:28 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
```

**Comment by velijv** [comment]
Tried restoring a snapshot to a previous period where the addon is not installed - it is still there.

**Comment by pvizeli** [comment]
Yes, looks like the add-on have no labels and also not set the ``legacy` mode. Will fix that, and after that you can remove it.
