### ISSUE TITLE
 Upgraded error for 0.77.3 to 0.78.1

### ISSUE THREAD

**Issue by asahajit** [home-assistant/hassio#711]
Upgraded from 0.77.3 to 0.78.1 and during start also  dev-info,dev-mqtt, dev-template,dev-event pages are not working

2018-09-21 14:58:18 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-09-21 14:58:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/discovery.py", line 168, in scan_devices
    results = await hass.async_add_job(_discover, netdisco)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/discovery.py", line 194, in _discover
    netdisco.scan()
  File "/usr/local/lib/python3.6/site-packages/netdisco/discovery.py", line 57, in scan
    self.ssdp.scan()
  File "/usr/local/lib/python3.6/site-packages/netdisco/ssdp.py", line 41, in scan
    self.update()
  File "/usr/local/lib/python3.6/site-packages/netdisco/ssdp.py", line 89, in update
    entry for entry in scan()
  File "/usr/local/lib/python3.6/site-packages/netdisco/ssdp.py", line 225, in scan
    for addr in zeroconf.get_all_addresses():
TypeError: get_all_addresses() missing 1 required positional argument: 'address_family'

**Comment by asahajit** [comment]
fixed in  0.78.2
