### ISSUE TITLE
Unable to uninstall the Add-on "Google Assistant Webserver"

### ISSUE THREAD

**Issue by ArnoutVerbeken** [home-assistant/hassio#715]
# Problem/Motivation

Unable to uninstall the Add-on "Google Assistant Webserver". 

## Expected behavior

Uninstall the add-on, should uninstall it. ;)

## Actual behavior

Errors are spawned.  I tried to uninstall over cli (SSH terminal) since I trust that more than the UI.
Error is: 
`error decoding json invalid character '<' looking for the beginning of value: <html><head><Title> 500 internal server Error</title></head><body><hl>500 internal server error</hl>Server got itself into trouble</body></html>`

Systemlog of HassIO is:

```
18-09-24 16:12:33 WARNING (MainThread) [hassio.api.security] /addons/fe49a976_google_assistant_webserver/uninstall no role for a0d7b954_ssh
18-09-24 16:12:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 122, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/utils.py", line 87, in wrap_check
    return await method(addon, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 674, in uninstall
    if not await self.instance.remove():
  File "/usr/local/lib/python3.7/site-packages/hassio/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/docker/interface.py", line 210, in _remove
    "Remove docker %s with latest and %s", self.image, self.version)
  File "/usr/local/lib/python3.7/site-packages/hassio/coresys.py", line 287, in __getattr__
    raise AttributeError(f"Can't resolve {name} on {self}")
AttributeError: Can't resolve version on <hassio.docker.addon.DockerAddon object at 0x74c4c7b0>
```

## Steps to reproduce

Install the Addon and try to uninstall it.
Addon can be found on https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274

## Proposed changes

I would not know, but I want to get rid of it....

**Comment by pvizeli** [comment]
Normaly exists a config flag for add-ons like this: `legacy: true`
