### ISSUE TITLE
Restart homeassistant service error

### ISSUE THREAD

**Issue by jyz0501** [home-assistant/hassio#723]
The homeassistant version I am using is 0.78.3. Every time I use the interface to restart the homeassistant service, I will get an error, so I can't restart homeassistant normally. Please help solve it. Thank you.
This problem ： https://github.com/home-assistant/home-assistant/issues/16822#issue-363237609

log:

```
2018-09-24 19:28:37 ERROR (MainThread) [homeassistant.components.hassio.handler] /homeassistant/check return code 500.
2018-09-24 19:28:37 ERROR (MainThread) [homeassistant.components.hassio] Hass.io config check API error
```

**Comment by pvizeli** [comment]
I  need the supervisor log

**Comment by jyz0501** [comment]
> I need the supervisor log

 ```
18-09-28 10:30:46 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py:617> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x719bd9e0>; the handler is closed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 621, in ping
    return await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 603, in _send_frame
    self.transport.write(header + message)
  File "uvloop/handles/stream.pyx", line 671, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x719bd9e0>; the handler is closed
18-09-28 10:30:51 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py:617> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x71884030>; the handler is closed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 621, in ping
    return await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 603, in _send_frame
    self.transport.write(header + message)
  File "uvloop/handles/stream.pyx", line 671, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x71884030>; the handler is closed
18-09-28 10:30:56 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py:617> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x719d1410>; the handler is closed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 621, in ping
    return await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 603, in _send_frame
    self.transport.write(header + message)
  File "uvloop/handles/stream.pyx", line 671, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x719d1410>; the handler is closed
18-09-28 10:31:02 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py:617> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x71a15410>; the handler is closed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 621, in ping
    return await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 603, in _send_frame
    self.transport.write(header + message)
  File "uvloop/handles/stream.pyx", line 671, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x71a15410>; the handler is closed
18-09-28 10:39:21 INFO (SyncWorker_9) [hassio.docker] Run command 'python3 -m homeassistant -c /config --script check_config' on homeassistant/raspberrypi3-homeassistant
18-09-28 10:40:06 ERROR (MainThread) [hassio.utils] Can't execute execute_command while a task is in progress
18-09-28 10:40:06 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 122, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/homeassistant.py", line 140, in check
    result = await self.sys_homeassistant.check_config()
  File "/usr/local/lib/python3.7/site-packages/hassio/homeassistant.py", line 359, in check_config
    if result.exit_code is None:
AttributeError: 'bool' object has no attribute 'exit_code'
18-09-28 10:40:07 ERROR (MainThread) [hassio.utils] Can't execute execute_command while a task is in progress
18-09-28 10:40:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 122, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/homeassistant.py", line 140, in check
    result = await self.sys_homeassistant.check_config()
  File "/usr/local/lib/python3.7/site-packages/hassio/homeassistant.py", line 359, in check_config
    if result.exit_code is None:
AttributeError: 'bool' object has no attribute 'exit_code'
18-09-28 10:40:07 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
18-09-28 10:40:08 ERROR (MainThread) [hassio.utils] Can't execute execute_command while a task is in progress
18-09-28 10:40:08 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 122, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/homeassistant.py", line 140, in check
    result = await self.sys_homeassistant.check_config()
  File "/usr/local/lib/python3.7/site-packages/hassio/homeassistant.py", line 359, in check_config
    if result.exit_code is None:
AttributeError: 'bool' object has no attribute 'exit_code'
```

**Comment by pvizeli** [comment]
Can you explain on what platform do you run hass.io and which version of docker?

**Comment by jyz0501** [comment]
> Can you explain on what platform do you run hass.io and which version of docker? And Hass.io version.
> 
> That look like a very old version and they should self update.

My hassio runs on version 131 and System is Resin OS 2.3.0 + rev1。

**Comment by pickeld** [comment]
hey, i get the same error. any update about it?
thank you

**Comment by pvizeli** [comment]
That is happens because there is a other job running for this container. Do you try to update is on same time?

**Comment by jyz0501** [comment]
> That is happens because there is a other job running for this container. Do you try to update it on same time?

ok, i see,It does not affect the use, it is not a big problem.
