### ISSUE TITLE
KeyError SSL while installing an addon

### ISSUE THREAD

**Issue by sholzmayer** [home-assistant/hassio#762]
Since the new version `136` installing my addons always fail with the following error code.

```
18-10-15 13:43:59 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 137, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/addons.py", line 148, in info
    ATTR_WEBUI: addon.webui,
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 309, in webui
    proto = 'https' if self.options[t_proto] else 'http'
KeyError: 'ssl'
```

Adding those `SSL`-properties to the addon `config.yaml` solves this problem.

```
"options": {
    "ssl": true
  },
  "schema": {
    "ssl": "bool"
  },
```

Any idea if this is a migration issue or due to a wrong addon-config?

**Comment by sholzmayer** [comment]
In the current version this is no longer an issue. I gonna close it. Thanks anyway!
