### ISSUE TITLE
discovery: Homekit Error in configurator.configurator

### ISSUE THREAD

**Issue by TomBrandt** [home-assistant/hassio#770]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/configurator.py", line 221, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/homekit_controller/__init__.py", line 195, in device_config_callback
    pairing_id)
  File "/usr/local/lib/python3.6/site-packages/homekit/protocol.py", line 94, in perform_pair_setup
    resp = connection.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
2018-10-17 21:41:30 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall configurator.configure (c:f9f477bbcf7146babba568043bb62828): configure_id=548480299192-1, fields=code=069-96-373>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/configurator.py", line 221, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/homekit_controller/__init__.py", line 195, in device_config_callback
    pairing_id)
  File "/usr/local/lib/python3.6/site-packages/homekit/protocol.py", line 94, in perform_pair_setup
    resp = connection.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
I know it worked fine in 0.79. but since the upgrade nope.
once you enter the home kit code it just sits there. I do notice service was called.

**Comment by TomBrandt** [comment]
I am working backwards on versions I was a 0.79.3 but upgraded and this issue appeared in 0.80.1, 0.80.0

this is the same error for each version
Timer got out of sync. Resetting
10:38 PM core.py (ERROR)
Error executing service <ServiceCall configurator.configure (c:221a82da13b14d879ea3e91574d60741): configure_id=547798199544-2, fields=code=069-96-373>
10:29 PM components/homekit_controller/__init__.py (ERROR)
Error fetching description at http://:50201/dial.xml
10:27 PM ssdp.py (WARNING)

I hope this helps. Clean image only changes to configuration file was location info and enable: Homkit.

**Comment by TomBrandt** [comment]
Works in 0.79.3
