### ISSUE TITLE
Error executing homeassistant.restart (>0.80)

### ISSUE THREAD

**Issue by Bakgrund** [home-assistant/hassio#786]
Running hassio 0.81.0 (also tried on 0.80.x) on a Raspberry pi 1 model b. Same issue as other users described in this thread: https://community.home-assistant.io/t/unable-to-restart-homeassistant-error-executing-service-servicecall-homeassistant-restart/73370/11

Calling the homeassistant.restart service will result in this error:

```
Error executing service <ServiceCall homeassistant.restart (c:36c5d84f4cc543d1b1c239b7ed44240e)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/__init__.py", line 264, in async_handle_core_service
    error = await async_check_config(hass)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/__init__.py", line 147, in async_check_config
    if result['result'] == "error":
UnboundLocalError: local variable 'result' referenced before assignment
```
If you try to bypass this by pulling the plug, it will refuse to boot, it does not connect to the network either.

**Comment by charlietomo** [comment]
I also have this issue.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/home-assistant/pull/18305
