### ISSUE TITLE
"Invalid Home Assistant config found!" when restarting hass.io

### ISSUE THREAD

**Issue by Febersoi** [home-assistant/hassio#811]
Hi,
I am running home-assistant on a Raspberry Pi 3 Model B with hassos and hass.io version 0.82.0.
I am using hass.io since some weeks now and I am always getting the same issue:

Everything works fine for a while, but after some time hass.io stops working completely and results in me having to install it again from scratch.
My system was running now for two days without any problems, but today when I wanted to add a new sonoff basic with tasmota the problem occured again.
When I try to change anything in my configuration and try to restart hass.io I get the following error:
`18-11-15 20:56:01 INFO (SyncWorker_0) [hassio.docker] Run command 'python3 -m homeassistant -c /config --script check_config' on homeassistant/raspberrypi3-homeassistant`
`18-11-15 20:58:15 ERROR (MainThread) [hassio.homeassistant] Invalid Home Assistant config found!`

Hass.io won't restart after this and in the info panel there is following error:

```
Thu Nov 15 2018 21:58:15 GMT+0100 (Mitteleuropäische Normalzeit)

INFO:homeassistant.util.package:Attempting install of colorlog==3.1.4
ERROR:homeassistant.util.package:Unable to install package colorlog==3.1.4: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/index.py", line 14, in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/html5lib/__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/html5lib/html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
Aborting script, could not install dependency colorlog==3.1.4
```

If I change my configuration.yaml back to the previous version (which was working before) the error remains.
I also tried the standard file from a new install, but it is still the same.
Everything else keeps working, my mqtt broker and zwave network is still running and I can use everything normaly.
If I now try to reboot my raspberry pi, home assistant won't start and I get a connection timeout.
Only the WebUI seems to be affected, I can still connect via SSH or Samba.

This error also occurs everytime I install an hass.io update.
I had to reinstall my homeassitant at least 5 times in the last 2 weeks.

**Comment by frenck** [comment]
I suspect your SD card to be corrupt.

**Comment by Febersoi** [comment]
Yes you are right. 
The problem was caused by a corrupt sd card, I changed to a different sd card and now it is running without problems.
Thanks a lot!
