### ISSUE TITLE
TP Link LB130 - unable to set colours which use the red LED

### ISSUE THREAD

**Issue by GoldilokZ** [home-assistant/hassio#833]
**Home Assistant release with the issue:**
0.82.1 (not sure if it happens with earlier versions as this is the first I've used Home Assist)

**Operating environment (HassOS/Generic):**
VMDK appliance running in a virtualbox VM
Currently running HassOS 1.13

**Description of problem:**
On the LB130 bulb, when trying to set any colour containing the red LED, it will not work.  Blue and green are fine, and the TPLink KASA app has no problems with colours containing red.

It appears the tplink platform is trying to give invalid values for the red LED... > 255

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/light/__init__.py", line 270, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/light/tplink.py", line 102, in turn_on
    self.smartbulb.hsv = hsv
  File "/usr/local/lib/python3.6/site-packages/pyHS100/smartbulb.py", line 148, in hsv
    '(valid range: 0-255)'.format(state[0]))
pyHS100.smartdevice.SmartDeviceException: Invalid hue value: 360 (valid range: 0-255)

**Comment by GoldilokZ** [comment]
Relevent config yaml.
light:
  - platform: tplink
    name: Computer Room
    host: localIPAddress
  - platform: tplink
    name: Wardrobe
    host: DifferentLocalIPAddress

**Comment by GoldilokZ** [comment]
accidentally closed....sorry am new at this.

**Comment by babichjacob** [comment]
This is a problem with the underlying `pyhs100` library. See [this pull request](https://github.com/GadgetReactor/pyHS100/pull/141) for discussion about fixing it (seems like they've figured it out but it just needs to be merged).
