### ISSUE TITLE
Hass.io frontend fails to load after upgrading to 0.84.5

### ISSUE THREAD

**Issue by grantalewis** [home-assistant/hassio#862]
**Home Assistant release with the issue:**
0.84.5

**Operating environment (HassOS/Generic):**
Hass.io, RPi3

**Supervisor logs:**
```
2018-12-20 09:32:15 WARNING (MainThread) [homeassistant.components.http] legacy_api_password support has been enabled. If you don't require it, remove the 'api_password' from your http config.
2018-12-20 09:32:17 WARNING (Recorder) [homeassistant.components.recorder.migration] Database is about to upgrade. Schema version: None
2018-12-20 09:33:34 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package home-assistant-frontend==20181211.2: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2860, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 330, in run
    self._warn_about_conflicts(to_install)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 456, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2871, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2880, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2862, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1788, in get_metadata
    raise KeyError("No metadata except PKG-INFO is available")
KeyError: 'No metadata except PKG-INFO is available'
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2018-12-20 09:33:34 ERROR (MainThread) [homeassistant.requirements] Not initializing frontend because could not install requirement home-assistant-frontend==20181211.2
2018-12-20 09:33:34 ERROR (MainThread) [homeassistant.setup] Setup failed for frontend: Could not install all requirements.
2018-12-20 09:33:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: binary_sensor.rachio31ddf8_online. Platform rachio does not generate unique IDs
2018-12-20 09:34:02 ERROR (MainThread) [homeassistant.loader] Unable to find component media_player.alexa
2018-12-20 09:34:07 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of logbook. Setup failed for dependencies: frontend
2018-12-20 09:34:07 ERROR (MainThread) [homeassistant.setup] Setup failed for logbook: Could not set up all dependencies.
2018-12-20 09:34:12 WARNING (MainThread) [homeassistant.setup] Setup of lutron is taking over 10 seconds.
2018-12-20 09:50:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1866327632] Received invalid command: get_panels
2018-12-20 09:50:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1866327632] Received invalid command: frontend/get_themes
2018-12-20 09:50:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1866327632] Received invalid command: frontend/get_translations
```

**Description of problem:**
Was running 0.83.3 without issue. Upgraded to 0.84.5 and encountered the above. 

I do run a couple of custom components but removed them from my config during the upgrade.

Configuration.yaml:
```
homeassistant:
  name: Home
  latitude: !secret my_latittuide
  longitude: !secret my_longitude
  elevation: 228
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
# Enables configuration UI
config:

ffmpeg:

timer:
  garage_door_timer:
    duration: '00:03:00'

zone: !include zones.yaml

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 4

# Enables the frontend
frontend:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - media_player.family_room_speaker
      - group.sonarr
      - remote.bedroom_harmony_hub
      - remote.living_room_harmony_hub

recorder:
  purge_interval: 2
  purge_keep_days: 2

# Discover some devices automatically
discovery:
   ignore:
     - plex_mediaserver
     - netgear_router
     - roku
     - samsung_tv
#     - ikea_tradfri

google_assistant:
  project_id: lewis-media-player
  #client_id: !secret google_assistant_client_id 
  #access_token: !secret google_assistant_access_token
  #agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - media_player
#    - switch
#    - light
#    - group
#  entity_config:
#    switch.kitchen:
#      name: Custom Name for Google Assistant
#      aliases:
#        - bright lights
#        - entry lights
#    light.living_room:
#      expose: false
#      room: living room

media_player:
  - platform: alexa
    email: !secret alexa_email
    password: !secret alexa_password
    url: amazon.com

zwave:
  usb_path: /dev/ttyACM0

# Emulated Hue allows Harmony Hub to interact with smart devices (LR fan, Kitchen lights, etc.)
emulated_hue:
  host_ip: 192.168.1.35
  listen_port: 8300

alexa:

remote:
  - platform: harmony
    name: Living Room Harmony Hub
    host: 192.168.1.13
    activity: Watch TV
  - platform: harmony
    name: Bedroom Harmony Hub
    host: 192.168.1.21
    activity: Watch TV

sensor: !include sensors.yaml

rachio:
  api_key: !secret rachio_api_key

binary_sensor:
  - platform: rachio

#panel_iframe:
#  nodered_flows:
#    title: Node-RED
#    url: "<redacted>"
#    icon: mdi:nodejs
#  rachio:
#    title: Rachio
#    url: "https://app.rach.io"
#    icon: mdi:water-pump

# Text to speech
tts:
  - platform: google

lutron:
  host: 192.168.1.225
  username: lutron
  password: integration

ios:

owntracks:
  track_new_devices: no
  max_gps_accuracy: 100
  waypoints: true

#device_tracker:
#  - platform: owntracks
#    track_new_devices: no
#    max_gps_accuracy: 100
#    waypoints: true
#  - platform: nmap_tracker
#    hosts:
#    - 192.168.1.196
#    - 192.168.1.197
#    - 192.168.1.198
#    - 192.168.1.199
#    interval_seconds: 30
# - platform: bluetooth_tracker

mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

camera:
- platform: ffmpeg
  name: Dining Room Camera
  input: -rtsp_transport tcp -i rtsp://admin:hAsI8G0b3hV7@192.168.1.51:554/Sms=2.unicast

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster

switch:
  - platform: mqtt
    name: "Garage Holiday"
    command_topic: "cmnd/sonoff_basic_01/power"
    state_topic: "stat/sonoff_basic_01/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Black Floor Fan"
    command_topic: "cmnd/sonoff_basic_02/power"
    state_topic: "stat/sonoff_basic_02/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Landscape Lights"
    command_topic: "cmnd/sonoff_basic_03/power"
    state_topic: "stat/sonoff_basic_03/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Attic Holiday Lights"
    command_topic: "cmnd/sonoff_basic_04/power"
    state_topic: "stat/sonoff_basic_04/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Edison Fan"
    command_topic: "cmnd/sonoff_basic_05/power"
    state_topic: "stat/sonoff_basic_05/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Sofa LEDs"
    command_topic: "cmnd/sonoff_basic_06/power"
    state_topic: "stat/sonoff_basic_06/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Sonoff Coffee"
    command_topic: "cmnd/sonoff_coffee/power"
    state_topic: "stat/sonoff_coffee/POWER"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Screen Door"
    command_topic: "cmnd/sonoff_sv_02/power"
    state_topic: "stat/sonoff_sv_02/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Toasty George"
    command_topic: "cmnd/sonoff_basic_07/power"
    state_topic: "stat/sonoff_basic_07/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
```

**Comment by grantalewis** [comment]
Fixed as per https://github.com/home-assistant/home-assistant/issues/16801
