### ISSUE TITLE
Home assistant unauthorized websocket

### ISSUE THREAD

**Issue by arissaraiva** [home-assistant/hassio#891]
**Home Assistant release with the issue:**
 rpi3, supervisor version 141

**Supervisor logs:**

**Description of problem:**

Hi to all since I updated to 0.84.6 I´m having problems with API´s, my cloud and google home don´t connect and neither my darksky the both show connection problems.

Look forward to fine a solution

rgds

**Comment by frenck** [comment]
Could you please provide some log information so we can actually look into the issue?

**Comment by arissaraiva** [comment]
sorry must have erased
here you go:

```
19-01-15 22:04:42 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-01-15 22:04:42 WARNING (MainThread) [hassio.api.proxy] Unauthorized WebSocket access
```
19-01-15 22:09:55 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-01-15 22:10:00 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize

**Comment by arissaraiva** [comment]
Hi yesterday I unisntalled a custom addon That I though was giving me problems and some of the logs changed:

Logs from supervisor:

```
-01-16 13:19:44 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: Cannot connect to host s3.amazonaws.com:443 ssl:None [Try again]

19-01-16 13:24:51 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-01-16 13:21:58 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: Cannot connect to host s3.amazonaws.com:443 ssl:None [Try again]
```
my hassio logs:

```
Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/cloud/iot.py", line 97, in connect
    yield from self._handle_connection()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/cloud/iot.py", line 153, in _handle_connection
    yield from hass.async_add_job(auth_api.check_token, self.cloud)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/cloud/auth_api.py", line 108, in check_token
    if cognito.check_token():
  File "/usr/local/lib/python3.6/site-packages/warrant/__init__.py", line 260, in check_token
    self.renew_access_token()
  File "/usr/local/lib/python3.6/site-packages/warrant/__init__.py", line 555, in renew_access_token
    AuthParameters=auth_params,
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 592, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
```
``Unable to connect to Dark Sky: HTTPSConnectionPool(host='api.darksky.net', port=443): Max retries exceeded with url: /forecast/b5dadd6836074028261ee0e4c44eb2fe/-23.5733,-46.6417?units=si&lang=en (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x728170d0>: Failed to establish a new connection: [Errno -3] Try again',))`

don´t know if this could help
`

**Comment by pvizeli** [comment]
What kind of host OS?

**Comment by arissaraiva** [comment]
Hi HassOS

**Comment by arissaraiva** [comment]
Good day, anything on this?

**Comment by pvizeli** [comment]
Can you post your Network configuration?

**Comment by arissaraiva** [comment]
Sorry I´m a bit of a newbie on everything, could be more especific what kind of configuration?

**Comment by arissaraiva** [comment]
don´t know if this fits the question but, I´m using duck DNS and it´s working fine, I have my 8123 and 443 ports router open for my hassio IP

**Comment by arissaraiva** [comment]
Hope I could find some help here, I can´t even update to 0.85

**Comment by arissaraiva** [comment]
anyone?
