### ISSUE TITLE
Home assistant isn't full working

### ISSUE THREAD

**Issue by simooooone** [home-assistant/hassio#986]
**Home Assistant release with the issue:**

0.90.1

**Operating environment (HassOS/Generic):**

core-ssh:~# hassio info
arch: armv7
channel: stable
hassos: "2.11"
homeassistant: 0.90.1
hostname: hassio
machine: raspberrypi3
supervisor: "150"
supported_arch:
- armv7
- armhf

**Supervisor logs:**

core-ssh:~# hassio su logs
19-03-31 13:22:36 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:22:36 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:22:36 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:22:41 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:22:41 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:22:41 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:22:46 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:22:46 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:22:46 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:22:51 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:22:51 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:22:51 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:22:56 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:22:56 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:22:56 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:01 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:01 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:01 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:06 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:06 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:06 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:11 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:11 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:11 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:16 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:17 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:17 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:22 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:22 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:22 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:27 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:27 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:27 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:32 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:32 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:32 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:35 INFO (MainThread) [hassio.api.security] /addons access from core_ssh
19-03-31 13:23:37 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:37 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:37 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:42 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:42 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:42 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:47 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:47 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:52 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:52 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:52 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:23:57 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:23:57 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:23:57 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:01 INFO (MainThread) [hassio.api.security] /homeassistant/restart access from core_ssh
19-03-31 13:24:02 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:02 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:02 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:04 INFO (SyncWorker_17) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.90.1                                                                                     
19-03-31 13:24:07 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:07 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:07 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:12 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:12 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:12 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:17 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:17 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:17 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:20 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-03-31 13:24:20 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]                                                            
19-03-31 13:24:20 INFO (MainThread) [hassio.auth] Home Assistant not running, check cache
19-03-31 13:24:20 INFO (MainThread) [hassio.auth] Cache hit for mqtt
19-03-31 13:24:22 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:22 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:22 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:27 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:27 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:27 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].                                                                             
19-03-31 13:24:32 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-03-31 13:24:32 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-03-31 13:24:32 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 13:24:32 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
19-03-31 13:24:35 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-03-31 13:25:09 INFO (MainThread) [hassio.api.security] /addons access from core_ssh
19-03-31 13:56:41 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-03-31 14:11:33 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-03-31 14:11:33 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/bestlibre/hassio-addons.git repository
19-03-31 14:11:33 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/home-assistant/hassio-addons repository
19-03-31 14:11:33 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/hassio-addons/repository repository
19-03-31 14:11:38 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: Cannot connect to host s3.amazonaws.com:443 ssl:None [Try again]
19-03-31 14:11:38 ERROR (MainThread) [hassio.addons.git] Can't update https://github.com/bestlibre/hassio-addons.git repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/bestlibre/hassio-addons.git/': Could not resolve host: github.com'.
19-03-31 14:11:38 ERROR (MainThread) [hassio.addons.git] Can't update https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': Could not resolve host: github.com'.
19-03-31 14:11:38 ERROR (MainThread) [hassio.addons.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.
19-03-31 14:11:39 INFO (MainThread) [hassio.addons] Load add-ons: 72 all - 0 new - 0 remove
19-03-31 14:14:22 INFO (MainThread) [hassio.api.security] /homeassistant/logs access from core_ssh
19-03-31 14:23:26 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh

**More logs**
hassio homeassistant 
check    info     logs     options  restart  start    stop     update   
core-ssh:~# hassio homeassistant logs
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.loader] Loaded google from homeassistant.components.google
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.loader] Loaded google.tts from homeassistant.components.google.tts
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.loader] Loaded sensor.yr from homeassistant.components.sensor.yr
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up zone
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.0 seconds.
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 0.0 seconds.
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up person
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up group
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.0 seconds.
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up cast
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setup of domain cast took 0.0 seconds.
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.yr
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up system_health
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up script
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up hassio
2019-03-31 15:24:23 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up config
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up automation
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up logbook
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up conversation
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up webhook
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up media_player
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain media_player took 0.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.2 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.loader] Loaded cast.media_player from homeassistant.components.cast.media_player
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 1.7 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.cast
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.3 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.loader] Loaded cloud.binary_sensor from homeassistant.components.cloud.binary_sensor
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.cloud
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 2.0 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.loader] Loaded panel_custom from homeassistant.components.panel_custom
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain person took 2.3 seconds.
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.1 seconds.
2019-03-31 15:24:25 INFO (SyncWorker_0) [pychromecast] Querying device status
2019-03-31 15:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 2.1 seconds.
2019-03-31 15:24:25 INFO (SyncWorker_12) [pychromecast] Querying device status
2019-03-31 15:24:25 INFO (SyncWorker_7) [pychromecast] Querying device status
2019-03-31 15:24:26 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 1.0 seconds.
2019-03-31 15:24:26 INFO (MainThread) [homeassistant.setup] Setting up default_config
2019-03-31 15:24:26 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.0 seconds.
2019-03-31 15:24:30 ERROR (MainThread) [homeassistant.components.sensor.yr] Retrying in 15 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-03-31 15:24:30 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 6.8 seconds.
2019-03-31 15:24:30 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 12.54s
2019-03-31 15:24:30 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2019-03-31 15:24:30 INFO (MainThread) [homeassistant.core] Timer:starting
2019-03-31 15:24:32 INFO (MainThread) [homeassistant.components.http.view] Serving /api/websocket to 172.30.32.2 (auth: False)
2019-03-31 15:24:32 INFO (MainThread) [homeassistant.components.http.view] Serving /auth/token to 172.30.32.2 (auth: False)
2019-03-31 15:26:20 ERROR (MainThread) [homeassistant.core] Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 609, in uvloop.loop.UVStream._on_eof
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)
2019-03-31 15:26:20 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error errno:1 reason: UNSUPPORTED_PROTOCOL
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)
2019-03-31 15:26:41 INFO (MainThread) [homeassistant.components.http.auth] api_password is going to deprecate. You need to use a bearer token to access /api/ from 172.30.32.2
2019-03-31 15:26:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:31:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:36:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:39:36 ERROR (MainThread) [homeassistant.components.sensor.yr] Retrying in 19 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-03-31 15:41:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:46:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:51:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:56:41 INFO (MainThread) [homeassistant.components.http.view] Serving /auth/token to 172.30.32.2 (auth: False)
2019-03-31 15:56:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 15:58:42 ERROR (MainThread) [homeassistant.components.sensor.yr] Retrying in 16 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-03-31 16:01:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 16:06:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 16:11:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 16:14:48 ERROR (MainThread) [homeassistant.components.sensor.yr] Retrying in 19 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-03-31 16:16:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 16:21:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 16:24:28 ERROR (MainThread) [homeassistant.components.updater] Could not contact Home Assistant Update to check for updates
2019-03-31 16:26:41 INFO (MainThread) [homeassistant.components.http.view] Serving /auth/token to 172.30.32.2 (auth: False)
2019-03-31 16:26:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)
2019-03-31 16:31:41 INFO (MainThread) [homeassistant.components.http.view] Serving /api/ to 172.30.32.2 (auth: True)

**Description of problem:**

can't connect to home assistant after a reboot, pi-hole working

**Comment by pvizeli** [comment]
Look like pihole affect your system. Please post your network configuration. If you use DHCP for HassOS, make a static configuration and don't use pihole for your HassOS device.

**Comment by simooooone** [comment]
The date is not correct, the time is UTC

**Comment by simooooone** [comment]
The date is correct. The time as you stated is UTC as explained here https://github.com/home-assistant/hassio/issues/638. Network configuration is router 192.168.1.1, Raspberry PI 3b+ with Hassio installed is 192.168.1.3 (setted at router level a static ip by mac address).
Inserted the CONFIG USB Key with wifi configuration (but it does not works), so I connected the Raspberry with an ethernet cable.
Until the hot unplug of the Raspberry all worked like a charm.

**Comment by wrightwells** [comment]
After first boot connected to ethernet, it installs 0.92.1 of HA and then cannot connect to the ethernet. It just gets into a reboot cycle.

**Comment by cogneato** [comment]
@simooooone Is it able to make connections when disabling pi-hole? It isn't enough to set a static ip from the router when you run the pi-hole addon. The static ip needs to be set on the host.

**Comment by simooooone** [comment]
> @simooooone Is it able to make connections when disabling pi-hole? It isn't enough to set a static ip from the router when you run the pi-hole addon. The static ip needs to be set on the host.

uninstalled pi-hole, motioneye, samba from command line
disabled http: configuration section and now I am able to enter hassio.local:8123
surely I made some mistakes in http section of the configuration.yaml file

**Comment by frenck** [comment]
> Is it able to make connections when disabling pi-hole? It isn't enough to set a static ip from the router when you run the pi-hole addon

@simooooone That is NOT a static IP. Setting a IP fixed in a DHCP server is called DHCP reservation. A static IP is configured manually on the device it self.

Not doing that as per manual of the add-on, will cause this issue.

Since this is not an Hass.io issue, I'll go ahead and close this report.
